Sync #6d4e543c
vuejs-translations/docs-zh-cn pull request #1005
Opened 2024-09-09 16:36 UTC by ikxin

## Description of Problem

https://github.com/vuejs/docs/compare/3ba5add9...6d4e543c

2024-09-09 16:40 UTC, ikxin commented
Vue 3.5 发布有一段时间了，我看到中文文档迟迟没有同步，所以我发起了这个 PR，翻译内容大部分是用了 ChatGPT，如有翻译不妥的地方还请指正，非常感谢

2024-09-10 01:32 UTC, KiritaniAyaka requested changes

2024-09-10 01:32 UTC, KiritaniAyaka commented on src/api/ssr.md
> +A special attribute that can be used to suppress [hydration mismatch](/guide/scaling-up/ssr#hydration-mismatch) warnings.
```suggestion
可以抑制[激活不匹配](/guide/scaling-up/ssr#hydration-mismatch)警告的特殊 attribute。
```

2024-09-10 01:32 UTC, KiritaniAyaka commented on src/api/ssr.md
> +- **Example**
```suggestion
- **示例**
```

2024-09-10 01:32 UTC, KiritaniAyaka commented on src/api/ssr.md
> +  If no value is provided, all types of mismatches will be allowed.
```suggestion
  值可以限制不匹配为特定类型。允许的值有：

  - `text`
  - `children`（仅允许直接子组件不匹配）
  - `class`
  - `style`
  - `attribute`

  如果没有提供值，则会允许所有类型的不匹配。
```

2024-09-10 01:32 UTC, KiritaniAyaka commented on src/api/utility-types.md
> +Extract prop types from a runtime props options object. The extracted types are public facing - i.e. the props that the parent is allowed to pass.
```suggestion
从运行时的 props 选项对象中提取 prop。提取的类型是面向外部的，即父组件允许传递的 props。
```

2024-09-10 01:32 UTC, KiritaniAyaka commented on src/guide/best-practices/performance.md
> +在 Vue 3.4 及更高版本中，计算属性只有在其计算值与上一个值不同时才会触发效果。例如，下面的 `isEven` 计算属性只有在返回的值从 `true` 变为 `false`，或者从 `false` 变为 `true` 时才会触发效果：
```suggestion
在 Vue 3.4 及更高版本中，计算属性仅在其计算值较前一个值发生更改时才会触发副作用。例如，以下 `isEven` 计算属性仅在返回值从 `true` 更改为 `false` 时才会触发副作用，反之亦然：
```

2024-09-10 01:32 UTC, KiritaniAyaka commented on src/guide/built-ins/teleport.md
> +In Vue 3.5 and above, we can use the `defer` prop to defer the target resolving of a Teleport until other parts of the application have mounted. This allows the Teleport to target a container element
```suggestion
## 延迟 Teleport <sup class="vt-badge" data-text="3.5+" /> {#deferred-teleport}

在 Vue 3.5 及更高版本中，我们可以使用 `defer` prop 推迟 Teleport 的目标解析，直到应用的其他部分挂载。这允许 Teleport 将由 Vue 渲染且位于组件树之后部分的容器元素作为目标：
```

2024-09-10 01:32 UTC, KiritaniAyaka commented on src/guide/built-ins/teleport.md
> +<!-- somewhere later in the template -->
```suggestion
<!-- 稍后出现于模板中的某处 -->
```

2024-09-10 01:32 UTC, KiritaniAyaka commented on src/guide/built-ins/teleport.md
> +Note that the target element must be rendered in the same mount / update tick with the Teleport - i.e. if the `<div>` is only mounted a second later, the Teleport will still report an error. The defe
```suggestion
请注意，目标元素必须与 Teleport 在同一个挂载/更新周期内渲染，即如果 `<div>` 只是在一秒后挂载，Teleport 仍然会报错。延迟 Teleport 的原理与 `mounted` 生命周期钩子类似。
```

2024-09-10 02:29 UTC, ikxin commented
@KiritaniAyaka 感谢建议

2024-09-10 03:19 UTC, KiritaniAyaka requested changes

2024-09-10 03:19 UTC, KiritaniAyaka commented on src/guide/typescript/composition-api.md
> +在无法进行自动推断的情况下，仍然可以通过通用参数将模板 ref 转换为显式类型。
```suggestion
在无法自动推断的情况下，仍然可以通过泛型参数将模板 ref 转换为显式类型。
```

2024-09-10 03:19 UTC, KiritaniAyaka commented on src/guide/typescript/composition-api.md
> +<summary>在 3.5 之前的版本使用</summary>
```suggestion
<summary>3.5 之前的用法</summary>
```

2024-09-10 03:19 UTC, KiritaniAyaka commented on src/guide/typescript/composition-api.md
> +为了获取导入组件的实例类型，我们需要先通过 `typeof` 获取其类型，然后使用 TypeScript 的内置 `InstanceType` 实用程序提取其实例类型：
```suggestion
为了获取导入组件的实例类型，我们需要先通过 `typeof` 获取其类型，然后使用 TypeScript 的内置 `InstanceType` 工具提取其实例类型：
```

2024-09-10 03:19 UTC, KiritaniAyaka commented on src/guide/essentials/watchers.md
> +有时我们可能会在观察器中执行副作用，例如异步请求：
```suggestion
有时我们可能会在侦听器中执行副作用，例如异步请求：
```

2024-09-10 03:19 UTC, KiritaniAyaka commented on src/guide/essentials/watchers.md
> +        // callback logic
```suggestion
        // 回调逻辑
```

2024-09-10 03:19 UTC, KiritaniAyaka commented on src/guide/essentials/watchers.md
> +    // callback logic
```suggestion
    // 回调逻辑
```

2024-09-10 03:19 UTC, KiritaniAyaka commented on src/guide/essentials/watchers.md
> +我们可以使用 [`onWatcherCleanup()`](/api/reactivity-core#onwatchercleanup) <sup class="vt-badge" data-text="3.5+" /> API 来注册一个清理函数，当 watcher 被无效并准备重新运行时会被调用：
```suggestion
但是如果在请求完成之前 `id` 发生了变化怎么办？当上一个请求完成时，它仍会使用已经过时的 ID 值触发回调。理想情况下，我们希望能够在 `id` 变为新值时取消过时的请求。

我们可以使用 [`onWatcherCleanup()`](/api/reactivity-core#onwatchercleanup) <sup class="vt-badge" data-text="3.5+" /> API 注册一个清理函数，它将在 watcher 无效并即将重新运行时被调用：
```

2024-09-10 03:19 UTC, KiritaniAyaka commented on src/guide/essentials/watchers.md
> +    // abort stale request
```suggestion
    // 回调逻辑
  })

  onWatcherCleanup(() => {
    // 终止过期请求
```

2024-09-10 03:19 UTC, KiritaniAyaka commented on src/guide/essentials/watchers.md
> +        // abort stale request
```suggestion
        // 回调逻辑
      })

      onWatcherCleanup(() => {
        // 终止过期请求
```

2024-09-10 03:19 UTC, KiritaniAyaka commented on src/guide/essentials/watchers.md
> +作为替代，`onCleanup` 函数还作为第三个参数传递给观察器回调函数，以及作为第一个参数传递给 `watchEffect` 效果函数：<span class="composition-api"></span>
```suggestion
请注意，`onWatcherCleanup` 仅在 Vue 3.5+ 中支持，并且必须在 `watchEffect` 效果函数或 `watch` 回调函数的同步执行期间调用：你不能在异步函数的 `await` 语句之后调用它。

作为替代，`onCleanup` 函数还作为侦听器回调的第三个参数<span class="composition-api">，以及 `watchEffect` 作用函数的第一个参数</span>：
```

2024-09-10 03:19 UTC, KiritaniAyaka commented on src/guide/essentials/watchers.md
> +    // cleanup logic
```suggestion
    // 清理逻辑
  })
})

watchEffect((onCleanup) => {
  // ...
  onCleanup(() => {
    // 清理逻辑
```

2024-09-10 03:19 UTC, KiritaniAyaka commented on src/guide/essentials/watchers.md
> +        // cleanup logic
```suggestion
        // 清理逻辑
```

2024-09-10 03:19 UTC, KiritaniAyaka commented on src/guide/essentials/watchers.md
> +这在 3.5 版本之前有效。另外，通过函数参数传递的 `onCleanup` 绑定到监视器实例，因此不受 `onWatcherCleanup` 的同步约束的束缚。
```suggestion
这在 3.5 之前的版本有效。此外，通过函数参数传递的 `onCleanup` 与侦听器实例相绑定，因此不受 `onWatcherCleanup` 的同步限制。
```

2024-09-10 03:46 UTC, Justineo requested changes

2024-09-10 03:46 UTC, Justineo commented on src/guide/components/async.md
> +  // instead of a single element
```suggestion
  // forEachElement 是一个遍历组件未激活的 DOM 中所有根元素的辅助函数，
  // 因为根元素可能是一个模板片段而非单个元素
```

2024-09-10 03:46 UTC, Justineo commented on src/guide/components/async.md
> +  // call `hydrate` when ready
```suggestion
  // 准备好时调用 `hydrate`
```

2024-09-10 03:46 UTC, Justineo commented on src/guide/components/async.md
> +    // return a teardown function if needed
```suggestion
    // 如必要，返回一个销毁函数
```

2024-09-10 03:46 UTC, Justineo commented on src/guide/components/props.md
> +Vue 的响应系统基于属性访问跟踪状态的使用情况。例如，在计算属性或观察者中访问 `props.foo` 时，`foo` 属性将被跟踪为依赖项。
```suggestion
Vue 的响应性系统基于 property 访问跟踪状态的使用情况。例如，在计算属性或侦听器 (watcher) 中访问 `props.foo` 时，`foo` 属性将被跟踪为依赖项。
```

按目前翻译约定，watcher 翻译的是侦听器，这里我觉得最好加入原文说明。

2024-09-10 03:46 UTC, Justineo commented on src/guide/components/props.md
> +在 3.4 版本及以下，`foo` 是一个实际的常量，永远不会改变。在 3.5 版本及以上，Vue 的编译器会自动在相同 `<script setup>` 块中访问由 `defineProps` 解构的变量时，在代码前自动添加 `props.`。因此，上面的代码等同于以下代码：
```suggestion
在 3.4 版本及以下，`foo` 是一个实际的常量，永远不会改变。在 3.5 版本及以上，Vue 的编译器会自动在同一个 `<script setup>` 块中访问由 `defineProps` 解构的变量时，在代码前自动添加 `props.`。因此，上面的代码等同于以下代码：
```

2024-09-10 03:46 UTC, Justineo commented on src/guide/components/props.md
> +  // re-runs when the "foo" prop changes in 3.5+
```suggestion
  // 在 3.5 之前只运行一次
  // 在 3.5+ 中在 "foo" prop 变化时重新执行
```

2024-09-10 03:46 UTC, Justineo commented on src/guide/components/props.md
> +  // `foo` transformed to `props.foo` by the compiler
```suggestion
  // `foo` 被编译器转换为 `props.foo`
```

2024-09-10 03:46 UTC, Justineo commented on src/guide/components/props.md
> +此外，您可以使用 JavaScript 的原生默认值语法为 props 声明默认值。当使用基于类型的 props 声明时，这是特别有用的。
```suggestion
此外，你可以使用 JavaScript 的原生默认值语法为 props 声明默认值。这在使用基于类型的 props 声明时非常有用。
```

2024-09-10 03:46 UTC, Justineo commented on src/guide/components/props.md
> +如果您希望在您的 IDE 中在解构的 props 和普通变量之间有更多视觉区分，Vue 的 VSCode 扩展提供了一个设置来启用解构 props 的内联提示。
```suggestion
如果你希望在您的 IDE 中在解构的 props 和普通变量之间有更多视觉上的区分，Vue 的 VSCode 扩展提供了一个设置来启用解构 props 的内联提示。
```

2024-09-10 03:46 UTC, Justineo commented on src/guide/components/props.md
> +由于它等价于 `watch(props.foo, ...)` - 我们传递的是一个值而不是一个响应式数据源给 `watch`，所以这并不会按预期工作。事实上，Vue 的编译器会捕捉这种情况并抛出警告。
```suggestion
由于它等价于 `watch(props.foo, ...)`——我们传递的是一个值而不是一个响应式数据源给 `watch`，所以这并不会按预期工作。事实上，Vue 的编译器会捕捉这种情况并抛出警告。
```

2024-09-10 03:46 UTC, Justineo commented on src/guide/components/props.md
> +与我们可以使用 `watch(() => props.foo, ...)` 监视普通 prop 类似，我们也可以通过将其包装在 getter 中来监视解构的 prop：
```suggestion
与我们可以使用 `watch(() => props.foo, ...)` 侦听普通 prop 类似，我们也可以通过将其包装在 getter 中来侦听解构的 prop：
```

2024-09-10 03:46 UTC, Justineo commented on src/guide/components/props.md
> +此外，这是推荐的方法，当我们需要将解构的 prop 传递到外部函数中并保持响应性时。
```suggestion
此外，当我们需要将解构的 prop 传递到外部函数中并保持响应性时，推荐的方法如下：
```

2024-09-10 03:46 UTC, Justineo commented on src/guide/components/props.md
> +外部函数在需要跟踪提供的属性的更改时可以调用 getter（或使用 [toValue](/api/reactivity-utilities.html#tovalue) 进行规范化）。例如，在计算属性或观察者的 getter 中。
```suggestion
外部函数可以调用 getter (或使用 [toValue](/api/reactivity-utilities.html#tovalue) 进行规范化) 来追踪提供的 prop 变更。例如，在计算属性或侦听器的 getter 中。
```

2024-09-10 03:46 UTC, Justineo commented on src/guide/essentials/template-refs.md
> +要使用 Composition API 获取引用，我们可以使用 [`useTemplateRef()`](/api/composition-api-helpers#usetemplateref) <sup class="vt-badge" data-text="3.5+" /> 助手：
```suggestion
要在组合式 API 中获取引用，我们可以使用辅助函数 [`useTemplateRef()`](/api/composition-api-helpers#usetemplateref) <sup class="vt-badge" data-text="3.5+" />：
```

2024-09-10 03:46 UTC, Justineo commented on src/guide/essentials/template-refs.md
> +<summary>Usage before 3.5</summary>
```suggestion
<summary>3.5 前的用法</summary>
```

2024-09-10 03:46 UTC, Justineo commented on src/guide/essentials/template-refs.md
> +在 3.5 版本之前，尚未引入 `useTemplateRef()`，我们需要声明一个与模板引用属性值匹配的引用。
```suggestion
在 3.5 版本之前，`useTemplateRef()` 尚未被引入，我们需要声明一个与模板引用属性值匹配的引用。
```

2024-09-10 03:46 UTC, Justineo commented on src/guide/essentials/template-refs.md
> +<summary>Usage before 3.5</summary>
```suggestion
<summary>3.5 前的用法</summary>
```

2024-09-10 03:46 UTC, Justineo commented on src/guide/essentials/template-refs.md
> +<summary>Usage before 3.5</summary>
```suggestion
<summary>3.5 前的用法</summary>
```

2024-09-10 03:46 UTC, Justineo commented on src/guide/essentials/template-refs.md
> +  // childRef.value will hold an instance of <Child />
```suggestion
  // childRef.value 将持有 <Child /> 的一个实例
```

2024-09-10 03:46 UTC, Justineo commented on src/guide/essentials/watchers.md
> +在 Vue 3.5+ 中，`deep` 选项还可以是一个数字，表示最大遍历深度 - 即 Vue 应该遍历对象嵌套属性的级数。
```suggestion
在 Vue 3.5+ 中，`deep` 选项还可以是一个数字，表示最大遍历深度——即 Vue 应该遍历对象嵌套属性的级数。
```

2024-09-10 03:46 UTC, Justineo commented on src/guide/essentials/watchers.md
> +有时我们可能会在观察器中执行副作用，例如异步请求：
```suggestion
有时我们可能会在侦听器中执行副作用，例如异步请求：
```

2024-09-10 03:46 UTC, Justineo commented on src/guide/essentials/watchers.md
> +    // callback logic
```suggestion
    // 回调逻辑
```

2024-09-10 03:46 UTC, Justineo commented on src/guide/essentials/watchers.md
> +        // callback logic
```suggestion
        // 回调逻辑
```

2024-09-10 03:46 UTC, Justineo commented on src/guide/essentials/watchers.md
> +但是如果在请求完成之前 `id` 发生了变化怎么办？ 当上一个请求完成时，它仍会使用已经过时的 ID 值触发回调。 理想情况下，我们希望能够在 `id` 变为新值时取消过时的请求。
```suggestion
但是如果在请求完成之前 `id` 发生了变化怎么办？当上一个请求完成时，它仍会使用已经过时的 ID 值触发回调。理想情况下，我们希望能够在 `id` 变为新值时取消过时的请求。
```

2024-09-10 03:46 UTC, Justineo commented on src/guide/essentials/watchers.md
> +我们可以使用 [`onWatcherCleanup()`](/api/reactivity-core#onwatchercleanup) <sup class="vt-badge" data-text="3.5+" /> API 来注册一个清理函数，当 watcher 被无效并准备重新运行时会被调用：
```suggestion
我们可以使用 [`onWatcherCleanup()`](/api/reactivity-core#onwatchercleanup) <sup class="vt-badge" data-text="3.5+" /> API 来注册一个清理函数，当侦听器失效并准备重新运行时会被调用：
```

2024-09-10 03:46 UTC, Justineo commented on src/guide/essentials/watchers.md
> +    // callback logic
```suggestion
    // 回调逻辑
```

2024-09-10 03:46 UTC, Justineo commented on src/guide/essentials/watchers.md
> +    // abort stale request
```suggestion
    // 退出过时请求
```

2024-09-10 03:46 UTC, Justineo commented on src/guide/essentials/watchers.md
> +        // callback logic
```suggestion
        // 回调逻辑
```

2024-09-10 03:46 UTC, Justineo commented on src/guide/essentials/watchers.md
> +        // abort stale request
```suggestion
        // 退出过时请求
```

2024-09-10 03:46 UTC, Justineo commented on src/guide/essentials/watchers.md
> +请注意，`onWatcherCleanup` 仅在 Vue 3.5+ 中支持，并且必须在 `watchEffect` 效果函数或 `watch` 回调函数的同步执行期间调用：您不能在异步函数的 `await` 语句之后调用它。
```suggestion
请注意，`onWatcherCleanup` 仅在 Vue 3.5+ 中支持，并且必须在 `watchEffect` 效果函数或 `watch` 回调函数的同步执行期间调用：不能在异步函数的 `await` 语句之后调用。
```

2024-09-10 03:46 UTC, Justineo commented on src/guide/essentials/watchers.md
> +    // cleanup logic
```suggestion
    // 清理逻辑
```

2024-09-10 03:46 UTC, Justineo commented on src/guide/essentials/watchers.md
> +    // cleanup logic
```suggestion
    // 清理逻辑
```

2024-09-10 03:46 UTC, Justineo commented on src/guide/essentials/watchers.md
> +        // cleanup logic
```suggestion
        // 清理逻辑
```

2024-09-10 03:46 UTC, Justineo commented on src/guide/essentials/watchers.md
> +这在 3.5 版本之前有效。另外，通过函数参数传递的 `onCleanup` 绑定到监视器实例，因此不受 `onWatcherCleanup` 的同步约束的束缚。
```suggestion
这在 3.5 版本之前有效。另外，通过函数参数传递的 `onCleanup` 绑定到侦听器实例，因此不受 `onWatcherCleanup` 的同步约束的束缚。
```

2024-09-10 03:46 UTC, Justineo commented on src/guide/extras/web-components.md
> +#### 应用程序级配置 <sup class="vt-badge" data-text="3.5+" /> {#app-level-config}
```suggestion
#### 应用级配置 <sup class="vt-badge" data-text="3.5+" /> {#app-level-config}
```

2024-09-10 03:46 UTC, Justineo commented on src/guide/extras/web-components.md
> +您可以使用 `configureApp` 选项来配置 Vue 自定义元素的应用程序实例：
```suggestion
可以使用 `configureApp` 选项来配置 Vue 自定义元素的应用实例：
```

2024-09-10 03:46 UTC, Justineo commented on src/guide/scaling-up/ssr.md
> +#### 抑制水合不匹配 <sup class="vt-badge" data-text="3.5+" /> {#suppressing-hydration-mismatches}
```suggestion
#### 消除激活不匹配 <sup class="vt-badge" data-text="3.5+" /> {#suppressing-hydration-mismatches}
```

2024-09-10 03:46 UTC, Justineo commented on src/guide/scaling-up/ssr.md
> +在 Vue 3.5+ 中，可以使用 [`data-allow-mismatch`](/api/ssr#data-allow-mismatch) 属性有选择地抑制无法避免的水合不匹配。
```suggestion
在 Vue 3.5+ 中，可以使用 [`data-allow-mismatch`](/api/ssr#data-allow-mismatch) 属性有选择性地消除无法避免的激活不匹配警告。
```

2024-09-10 03:46 UTC, Justineo commented on src/guide/typescript/composition-api.md
> +当使用基于类型的声明时，我们失去了为 props 声明默认值的能力。可以通过使用[响应式 Props 解构](/guide/components/props#reactive-props-destructure)解决这个问题。 <sup class="vt-badge" data-text="3.5+" />:
```suggestion
当使用基于类型的声明时，我们失去了为 props 声明默认值的能力。可以通过使用[响应式 Props 解构](/guide/components/props#reactive-props-destructure)解决这个问题。 <sup class="vt-badge" data-text="3.5+" />：
```

2024-09-10 03:46 UTC, Justineo commented on src/guide/typescript/composition-api.md
> +请注意，在使用 `withDefaults` 时，默认值的可变引用类型（如数组或对象）应该在函数中进行包装，以避免意外修改和外部副作用。这样可以确保每个组件实例都会获得自己默认值的副本。当使用解构时，这**不**是必要的。
```suggestion
请注意，在使用 `withDefaults` 时，默认值的可变引用类型 (如数组或对象) 应该在函数中进行包装，以避免意外修改和外部副作用。这样可以确保每个组件实例都会获得自己默认值的副本。当使用解构时，这**不**是必要的。
```

2024-09-10 03:46 UTC, Justineo commented on src/guide/typescript/composition-api.md
> +使用 Vue 3.5 和 `@vue/language-tools` 2.1（为 IDE 语言服务和 `vue-tsc` 提供支持），在单文件组件中，`useTemplateRef()` 创建的 ref 类型可以根据匹配的 `ref` 属性使用的元素**自动推断**为静态 ref。
```suggestion
在 Vue 3.5 和 @vue/language-tools 2.1 (为 IDE 语言服务和 vue-tsc 提供支持) 中，在 SFC 中由 `useTemplateRef()` 创建的 ref 类型可以基于匹配的 ref attribute 所在的元素**自动推断**为静态类型。
```

2024-09-10 03:46 UTC, Justineo commented on src/guide/typescript/composition-api.md
> +<summary>在 3.5 之前的版本使用</summary>
```suggestion
<summary>3.5 前的用法</summary>
```

2024-09-10 03:46 UTC, Justineo commented on src/guide/typescript/composition-api.md
> +通过 Vue 3.5 和 `@vue/language-tools` 2.1（用于 IDE 语言服务和 `vue-tsc`）自动生成推断的 refs 类型，这将应用在基于 `ref` 属性使用的元素或组件的静态 refs 上，故在 SFC 中使用 `useTemplateRef()` 会**自动推断** ref 类型。
```suggestion
在 Vue 3.5 和 @vue/language-tools 2.1 (为 IDE 语言服务和 vue-tsc 提供支持) 中，在 SFC 中由 `useTemplateRef()` 创建的 ref 类型可以基于匹配的 ref attribute 所在的元素**自动推断**为静态类型。
```

2024-09-10 03:46 UTC, Justineo commented on src/guide/typescript/composition-api.md
> +在无法自动推断的情况下（如非 SFC 使用或动态组件），您可以通过泛型参数将模板 ref 强制转换为显式类型。
```suggestion
在无法自动推断的情况下 (如非 SFC 使用或动态组件)，仍然可以通过泛型参数将模板 ref 强制转换为显式类型。
```

2024-09-10 03:46 UTC, Justineo commented on src/guide/typescript/composition-api.md
> +在无法进行自动推断的情况下，仍然可以通过通用参数将模板 ref 转换为显式类型。
```suggestion
在无法自动推断的情况下 (如非 SFC 使用或动态组件)，仍然可以通过泛型参数将模板 ref 强制转换为显式类型。
```

2024-09-10 03:46 UTC, Justineo commented on src/guide/typescript/composition-api.md
> +为了获取导入组件的实例类型，我们需要先通过 `typeof` 获取其类型，然后使用 TypeScript 的内置 `InstanceType` 实用程序提取其实例类型：
```suggestion
为了获取导入组件的实例类型，我们需要先通过 `typeof` 获取其类型，然后使用 TypeScript 的内置 `InstanceType` 工具类型提取其实例类型：
```

2024-09-10 03:46 UTC, Justineo commented on src/guide/typescript/composition-api.md
> +Note that with `@vue/language-tools` 2.1+, static template refs' types can be automatically inferred and the above is only needed in edge cases.
```suggestion
请注意在 `@vue/language-tools` 2.1 以上版本中，静态模板 ref 的类型可以被自动推导，上述这些仅在极端情况下需要。
```

2024-09-10 03:50 UTC, Justineo commented on src/api/built-in-components.md
> +  推迟解析目标 <sup class="vt-badge" data-text="3.5+" />:
```suggestion
  延迟目标解析 <sup class="vt-badge" data-text="3.5+" />：
```

2024-09-10 03:51 UTC, Justineo commented on src/api/built-in-directives.md
> +  - 值可以省略（当 attribute 和绑定的值同名时，需要 3.4+ 版本）
```suggestion
  - 值可以省略 (当 attribute 和绑定的值同名时，需要 3.4+ 版本)
```

2024-09-10 03:52 UTC, Justineo commented on src/api/built-in-directives.md
> +  - `.attr` - 强制绑定为 DOM attribute（3.2+）。
```suggestion
  - `.prop` - 强制绑定为 DOM property (3.2+)。
  - `.attr` - 强制绑定为 DOM attribute (3.2+)。
```

2024-09-10 03:56 UTC, Justineo commented on src/guide/components/async.md
> +可以选择传递一个观察者的选项对象值：
```suggestion
可以选择传递一个侦听器的选项对象值：
```

2024-09-10 04:14 UTC, Justineo commented on src/api/composition-api-helpers.md
> +<!-- TODO: translation -->
```suggestion
<!-- TODO: translation -->
```

2024-09-10 04:14 UTC, Justineo commented on src/api/custom-elements.md
> +<!-- TODO: translation -->
```suggestion
<!-- TODO: translation -->
```

2024-09-10 04:23 UTC, Justineo commented on src/guide/components/props.md
> +如果你希望在您的 IDE 中在解构的 props 和普通变量之间有更多视觉上的区分，Vue 的 VSCode 扩展提供了一个设置来启用解构 props 的内联提示。
```suggestion
如果你希望在 IDE 中在解构的 props 和普通变量之间有更多视觉上的区分，Vue 的 VSCode 扩展提供了一个设置来启用解构 props 的内联提示。
```

2024-09-10 04:25 UTC, Justineo approved these changes

2024-09-10 09:22 UTC, KiritaniAyaka approved these changes

2024-09-10 09:34 UTC, merged