docs: translate custom-elements.md
vuejs-translations/docs-zh-cn pull request #1013
Opened 2024-09-11 01:24 UTC by ikxin

### 在创建 pull request 之前

请确认：

- [x] 我已经阅读过项目的 [wiki](https://github.com/vuejs-translations/docs-zh-cn/wiki) 了解相关注意事项。
- [x] 我对翻译内容的改动不包含基于英文原版的扩展、删减或演绎 (如有，请移步至[英文文档仓库](https://github.com/vuejs/docs)讨论，相关结论会被定期从英文版同步)

### 问题描述

2024-09-11 12:36 UTC, KiritaniAyaka requested changes

2024-09-11 12:36 UTC, KiritaniAyaka commented on src/api/custom-elements.md
> +此方法接受与 [`defineComponent`](#definecomponent) 相同参数，但返回一个原生 [Custom Element](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements) 类构造函数。
```suggestion
此方法接受的参数与 [`defineComponent`](#definecomponent) 相同，但返回一个原生 [Custom Element](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements) 类构造函数。
```

2024-09-11 12:36 UTC, KiritaniAyaka commented on src/api/custom-elements.md
> +  - **`shadowRoot`** <sup class="vt-badge" data-text="3.5+"/>: `boolean`，默认为 `true`。设置为 `false` 以在不带阴影根的情况下渲染自定义元素。这意味着自定义元素 SFCs 中的 `<style>` 将不再被封装。
```suggestion
  - **`shadowRoot`** <sup class="vt-badge" data-text="3.5+"/>: `boolean`，默认为 `true`。设置为 `false` 以在不带阴影根的情况下渲染自定义元素。这意味着自定义元素单文件组件中的 `<style>` 将不再被封装。
```

#940

2024-09-11 12:36 UTC, KiritaniAyaka commented on src/api/custom-elements.md
> +  - 请注意，使用 Single-File Components 时，`defineCustomElement()` 需要 [特殊配置](/guide/extras/web-components#sfc-as-custom-element)。
```suggestion
  - 请注意，使用单文件组件时，`defineCustomElement()` 需要 [特殊配置](/guide/extras/web-components#sfc-as-custom-element)。
```

#940

2024-09-11 12:36 UTC, KiritaniAyaka commented on src/api/custom-elements.md
> +  注意，这些选项不是作为组件本身的一部分传递，也可以通过第二个参数传递：
```suggestion
  注意，这些选项也可以不作为组件本身的一部分传递，而是通过第二个参数传递：
```

2024-09-11 12:36 UTC, KiritaniAyaka commented on src/api/custom-elements.md
> +一个 Composition API 助手，返回当前 Vue 自定义元素的主元素。
```suggestion
一个 Composition API 助手，返回当前 Vue 自定义元素的宿主元素。
```

2024-09-11 12:36 UTC, KiritaniAyaka commented on src/api/custom-elements.md
> +一个 Options API 属性，公开当前 Vue 自定义元素的主元素。
```suggestion
一个 Options API 属性，公开当前 Vue 自定义元素的宿主元素。
```

2024-09-12 05:22 UTC, Justineo requested changes

2024-09-12 05:22 UTC, Justineo commented on src/api/custom-elements.md
> +  除了标准组件选项，`defineCustomElement()` 还支持一系列特定于自定义元素的选项：
```suggestion
  除了常规的组件选项，`defineCustomElement()` 还支持一系列特定于自定义元素的选项：
```

2024-09-12 05:22 UTC, Justineo commented on src/api/custom-elements.md
> +  - **`configureApp`** <sup class="vt-badge" data-text="3.5+"/>: 一个函数，可用于配置自定义元素的 Vue 应用实例。
```suggestion
  - **`configureApp`** <sup class="vt-badge" data-text="3.5+"/>：一个函数，可用于配置自定义元素的 Vue 应用实例。
```

2024-09-12 05:22 UTC, Justineo commented on src/api/custom-elements.md
> +  - **`shadowRoot`** <sup class="vt-badge" data-text="3.5+"/>: `boolean`，默认为 `true`。设置为 `false` 以在不带阴影根的情况下渲染自定义元素。这意味着自定义元素单文件组件中的 `<style>` 将不再被封装。
```suggestion
  - **`shadowRoot`** <sup class="vt-badge" data-text="3.5+"/>: `boolean`，默认为 `true`。设置为 `false` 以在不带 shadow root 的情况下渲染自定义元素。这意味着自定义元素单文件组件中的 `<style>` 将不再被封装隔离。
```

这里光说“封装”可能不太能表达完整意思，意译了一下。

2024-09-12 05:22 UTC, Justineo commented on src/api/custom-elements.md
> +  - **`nonce`** <sup class="vt-badge" data-text="3.5+"/>: `string`，如果提供，将作为注入到阴影根的样式标签上的 `nonce` 属性。
```suggestion
  - **`nonce`** <sup class="vt-badge" data-text="3.5+"/>: `string`，如果提供，将在注入到 shadow root 样式标签上设置 `nonce` attribute。
```

2024-09-12 05:22 UTC, Justineo commented on src/api/custom-elements.md
>    ```
代码里的注释也要翻译一下

2024-09-12 05:22 UTC, Justineo commented on src/api/custom-elements.md
> +  - 请注意，使用单文件组件时，`defineCustomElement()` 需要 [特殊配置](/guide/extras/web-components#sfc-as-custom-element)。
```suggestion
  - 请注意，使用单文件组件时，`defineCustomElement()` 需要进行[特殊配置](/guide/extras/web-components#sfc-as-custom-element)。
```

2024-09-12 05:22 UTC, Justineo commented on src/api/custom-elements.md
> +一个 Composition API 助手，返回当前 Vue 自定义元素的宿主元素。
```suggestion
一个组合式 API 辅助函数，返回当前 Vue 自定义元素的宿主元素。
```

2024-09-12 05:22 UTC, Justineo commented on src/api/custom-elements.md
> +一个 Composition API 助手，返回当前 Vue 自定义元素的阴影根。
```suggestion
一个组合式 API 辅助函数，返回当前 Vue 自定义元素的 shadow root。
```

2024-09-12 05:22 UTC, Justineo commented on src/api/custom-elements.md
> +一个 Options API 属性，公开当前 Vue 自定义元素的宿主元素。
```suggestion
一个选项式 API 的 property，暴露当前 Vue 自定义元素的宿主元素。
```

2024-09-12 06:44 UTC, ikxin commented
@Justineo done

2024-09-12 06:57 UTC, Justineo commented on src/api/custom-elements.md
> +    // 以下选项为 3.5+ 版本
```suggestion
    // 以下选项在 3.5+ 版本中支持
```

2024-09-12 07:40 UTC, KiritaniAyaka commented on src/api/custom-elements.md
> +一个 Composition API 助手，返回当前 Vue 自定义元素的阴影根。
不翻译 shadow root 是不是也可以加到术语翻译约定中，目前表格里还没有这项

2024-09-12 07:40 UTC, Justineo requested changes

2024-09-12 07:40 UTC, Justineo commented on src/api/custom-elements.md
> +此方法接受的参数与 [`defineComponent`](#definecomponent) 相同，但返回一个原生 [Custom Element](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements) 类构造函数。
```suggestion
此方法接受的参数与 [`defineComponent`](#definecomponent) 相同，但返回一个原生[自定义元素](https://developer.mozilla.org/zh-CN/docs/Web/Web_Components/Using_custom_elements)类构造函数。
```

2024-09-12 07:40 UTC, Justineo commented on src/api/custom-elements.md
> +  返回值是一个自定义元素构造函数，可以使用 [`customElements.define()`](https://developer.mozilla.org/en-US/docs/Web/API/CustomElementRegistry/define) 注册。
```suggestion
  返回值是一个自定义元素构造函数，可以使用 [`customElements.define()`](https://developer.mozilla.org/zh-CN/docs/Web/API/CustomElementRegistry/define) 注册。
```

2024-09-12 07:41 UTC, KiritaniAyaka requested changes

2024-09-12 07:41 UTC, KiritaniAyaka commented on src/api/custom-elements.md
> +  - **`styles`**: 一个内联 CSS 字符串数组，用于提供应注入元素阴影根的 CSS。
```suggestion
  - **`styles`**: 一个内联 CSS 字符串数组，用于提供应注入元素 shadow root 的 CSS。
```

2024-09-12 07:42 UTC, Justineo requested changes

2024-09-12 07:42 UTC, Justineo commented on src/api/custom-elements.md
> +  - **`styles`**: 一个内联 CSS 字符串数组，用于提供应注入元素阴影根的 CSS。
```suggestion
  - **`styles`**：一个内联 CSS 字符串数组，用于提供应注入元素阴影根的 CSS。
```

2024-09-12 07:42 UTC, Justineo commented on src/api/custom-elements.md
> +  - **`shadowRoot`** <sup class="vt-badge" data-text="3.5+"/>: `boolean`，默认为 `true`。设置为 `false` 以在不带 shadow root 的情况下渲染自定义元素。这意味着自定义元素单文件组件中的 `<style>` 将不再被封装隔离。
```suggestion
  - **`shadowRoot`** <sup class="vt-badge" data-text="3.5+"/>：`boolean`，默认为 `true`。设置为 `false` 以在不带 shadow root 的情况下渲染自定义元素。这意味着自定义元素单文件组件中的 `<style>` 将不再被封装隔离。
```

2024-09-12 07:45 UTC, merged