Sync #f9c82f48
vuejs-translations/docs-zh-cn pull request #1054
Opened 2024-12-06 07:47 UTC by veaba

## Description of Problem

https://github.com/vuejs/docs/compare/6d4e543c...f9c82f48

2024-12-07 15:14 UTC, KiritaniAyaka requested changes

2024-12-07 15:14 UTC, KiritaniAyaka commented on src/guide/reusability/custom-directives.md
> +// make v-highlight usable in all components
```suggestion
// 使 v-highlight 在所有组件中都可用
```

2024-12-07 15:14 UTC, KiritaniAyaka commented on src/guide/reusability/custom-directives.md
> +在可能的情况下，建议使用内置指令如 `v-bind` 进行声明式模板，因为它们更高效，对服务器渲染也更友好。
```suggestion
建议尽可能使用 `v-bind` 等内置指令声明模板，因为它们更高效，对服务端渲染也更友好。
```

2024-12-07 15:14 UTC, KiritaniAyaka commented on src/guide/reusability/custom-directives.md
> +A common example of this is a `v-focus` custom directive that brings an element into focus.
```suggestion
只有当所需功能只能通过直接的 DOM 操作来实现时，才应该使用自定义指令。

一个常见例子是使元素获取焦点的 `v-focus` 指令。
```

2024-12-07 15:14 UTC, KiritaniAyaka commented on src/guide/scaling-up/testing.md
> +- [Playwright](https://playwright.dev/) 也是一个非常好的端到端测试解决方案，支持所有的现代渲染引擎，包括 Chromium、WebKit 和 Firefox。在 Windows、Linux 和 macOS 上进行本地或 CI 测试、无头测试，或使用适用于 Android 和 Mobile Safari 的 Google Chrome 的原生移动端模拟测试。
```suggestion
- [Playwright](https://playwright.dev/) 是一个非常好的端到端测试解决方案，支持 Chromium、WebKit 和 Firefox。在 Windows、Linux 和 macOS 上进行本地或 CI 测试、无头测试，或使用适用于 Android 和 Mobile Safari 的 Google Chrome 的原生移动端模拟测试。它拥有信息丰富的用户界面、出色的调试能力、内置断言、并行处理功能以及追踪功能，旨在消除不稳定的测试。它还提供对[组件测试](https://docs.cypress.io/guides/component-testing/introduction)的支持，但目前处于实验阶段。Playwright 由微软开源并维护。
```

2024-12-07 15:14 UTC, KiritaniAyaka commented on src/guide/scaling-up/testing.md
> +- [Cypress](https://www.cypress.io/) 具有信息丰富的图形界面、出色的调试性、内置断言、存根、抗剥落性、并行化和快照等诸多特性。而且如上所述，它还提供对 [组件测试](https://docs.cypress.io/guides/component-testing/introduction) 的支持。它支持基于 Chromium 的浏览器、Firefox 和 E
```suggestion
- [Cypress](https://www.cypress.io/) 具有信息丰富的图形界面、出色的调试性、内置断言、存根、抗剥落性、并行化和快照等诸多特性。而且如上所述，它还提供对 [组件测试](https://docs.cypress.io/guides/component-testing/introduction) 的支持。它支持基于 Chromium 的浏览器、Firefox 和 Electron。但 WebKit 被标记为实验性支持。Cypress 采用 MIT 许可，但并行化等部分功能需要订阅 Cypress Cloud。
```

2024-12-09 08:55 UTC, veaba reviewed
apply the suggustions.

2024-12-09 09:02 UTC, veaba commented on src/guide/extras/web-components.md
> +## 非 Vue Web Components 和 TypeScript {#non-vue-web-components-and-typescript}
待翻译

2024-12-30 03:05 UTC, Jinjiang commented on src/guide/reusability/custom-directives.md
> +在 `<script setup>` 中，任何以 `v` 开头的驼峰式命名的变量都可以当作自定义指令使用。在上述例子中，`vHighlight` 可以在模板中以 `v-highlight`的形式使用。
```suggestion
在 `<script setup>` 中，任何以 `v` 开头的驼峰式命名的变量都可以当作自定义指令使用。在上述例子中，`vHighlight` 可以在模板中以 `v-highlight` 的形式使用。
```

2024-12-30 03:07 UTC, merged

2024-12-30 10:19 UTC, veaba commented
close #967
see https://github.com/vuejs-translations/docs-zh-cn/commit/7d926de67b7d9895f2b59c614133b83ace993af3