docs(application): review src\guide\essentials\application.md
vuejs-translations/docs-zh-cn pull request #17
Opened 2022-01-17 00:21 UTC by KimYangOfCat

#15 finished

2022-01-17 06:26 UTC, wxsms requested changes

2022-01-17 06:26 UTC, wxsms commented on src/guide/essentials/application.md
> +我们传入 `createApp` 的对象实际上是一个组件，每个应用都需要一个 “根组件”，其他组件将作为其子组件。
```suggestion
我们传入 `createApp` 的对象实际上是一个组件，每个应用都需要一个“根组件”，其他组件将作为其子组件。
```

引号可以不加空格。见 [wiki](https://github.com/vuejs-translations/docs-zh-cn/wiki/%E7%BF%BB%E8%AF%91%E9%A1%BB%E7%9F%A5#24-%E7%A9%BA%E6%A0%BC%E7%9A%84%E4%BD%BF%E7%94%A8)

2022-01-17 06:26 UTC, wxsms commented on src/guide/essentials/application.md
> +虽然本指引中的许多示例只需要一个组件，但大多数真实的应用程序都是由一颗嵌套的可重用的组件树组成的。例如，待办事项应用程序的组件树可能是这样的：
```suggestion
虽然本指引中的许多示例只需要一个组件，但大多数真实的应用都是由一颗嵌套的、可重用的组件树组成的。例如，待办事项应用程序的组件树可能是这样的：
```

应用程序应简写为应用，见 [wiki](https://github.com/vuejs-translations/docs-zh-cn/wiki/%E7%BF%BB%E8%AF%91%E9%A1%BB%E7%9F%A5#14-%E4%B8%AD%E6%96%87%E6%9C%AF%E8%AF%AD%E7%BA%A6%E5%AE%9A)

2022-01-17 06:26 UTC, wxsms commented on src/guide/essentials/application.md
> +该方法接收一个 “容器” 参数，可以是一个实际的 DOM 元素或是一个 CSS 选择器字符串。
```suggestion
该方法接收一个“容器” 参数，可以是一个实际的 DOM 元素或是一个 CSS 选择器字符串：
```

2022-01-17 06:26 UTC, wxsms commented on src/guide/essentials/application.md
> +`.mount()` 方法应该始终在整个应用配置和资源注册完成后被调用。同时请注意，不同于其他资源注册方法，它的返回值是根组件实例而非应用实例，。
```suggestion
`.mount()` 方法应该始终在整个应用配置和资源注册完成后被调用。同时请注意，不同于其他资源注册方法，它的返回值是根组件实例而非应用实例。
```

2022-01-17 06:26 UTC, wxsms commented on src/guide/essentials/application.md
> +当未采用构建流程仍想使用 Vue 时，我们可以在挂载容器中直接书写组件模板：
```suggestion
当在未采用构建流程的情况下使用 Vue 时，我们可以在挂载容器中直接书写根组件模板：
```

2022-01-17 06:26 UTC, wxsms commented on src/guide/essentials/application.md
> +如果根组件没有设置 `template`值时 ，Vue 会自动使用容器的 `innerHTML` 作为模板。
```suggestion
当根组件没有设置 `template` 选项的值时 ，Vue 将自动使用容器的 `innerHTML` 作为模板。
```

2022-01-17 06:26 UTC, wxsms commented on src/guide/essentials/application.md
> +应用实例会暴露一个 `.config` 对象来让我们能够配置一些应用级的选项，例如定义一个应用级的错误处理器，它将捕获所有由子组件上抛而未被处理的错误。
```suggestion
应用实例会暴露一个 `.config` 对象来让我们能够配置一些应用级的选项，例如定义一个应用级的错误处理器，它将捕获所有由子组件上抛而未被处理的错误：
```

2022-01-17 06:26 UTC, wxsms commented on src/guide/essentials/application.md
> +应用实例还提供了一些方法来注册应用全局可用的资源，例如注册一个组件：
```suggestion
应用实例还提供了一些方法来注册应用范围内可用的资源，例如注册一个组件：
```

app-scoped 感觉不应该翻译为“应用全局”

2022-01-17 06:26 UTC, wxsms commented on src/guide/essentials/application.md
> +确保在挂载应用实例之前应用所有的应用程序配置！
```suggestion
确保在挂载应用实例之前完成所有应用配置！
```

这里一句话三个“应用”感觉有点怪。稍微调整了一下。

2022-01-17 09:31 UTC, wxsms approved these changes

2022-01-19 16:53 UTC, Jinjiang commented
发现有 conflict 👀

2022-01-20 03:14 UTC, KimYangOfCat commented
@Jinjiang 已解决

2022-01-25 05:11 UTC, watonyweng commented on src/guide/essentials/application.md
> +你不必再受限于一个页面只能拥有一个应用实例。`createApp` API 允许多个 Vue 应用共存于同一个页面上，它们每一个都是隔离的，有自己的配置和全局资源。
```suggestion
你不必再受限于一个页面只能拥有一个应用实例。`createApp` API 允许多个 Vue 应用共存于同一个页面上，它们每一个应用实例都是隔离的，有自己的配置和全局资源。
```

2022-02-02 04:20 UTC, Jinjiang commented on src/guide/essentials/application.md
> +虽然本指引中的许多示例只需要一个组件，但大多数真实的应用都是由一颗嵌套的、可重用的组件树组成的。例如，待办事项应用程序的组件树可能是这样的：
指引 -> 指南
下同

2022-02-02 04:20 UTC, Jinjiang commented on src/guide/essentials/application.md
> +该方法接收一个“容器”参数，可以是一个实际的 DOM 元素或是一个 CSS 选择器字符串：
这里没有必要折行，建议和原文保持一致

2022-02-02 04:20 UTC, Jinjiang commented on src/guide/essentials/application.md
> +当根组件没有设置 `template` 选项的值时 ，Vue 将自动使用容器的 `innerHTML` 作为模板。
```suggestion
当根组件没有设置 `template` 选项时，Vue 将自动使用容器的 `innerHTML` 作为模板。
```

2022-02-02 04:20 UTC, Jinjiang commented on src/guide/essentials/application.md
> +应用实例会暴露一个 `.config` 对象来让我们能够配置一些应用级的选项，例如定义一个应用级的错误处理器，它将捕获所有由子组件上抛而未被处理的错误：
```suggestion
应用实例会暴露一个 `.config` 对象允许我们配置一些应用级的选项，例如定义一个应用级的错误处理器，它将捕获所有由子组件上抛而未被处理的错误：
```

2022-02-02 04:20 UTC, Jinjiang commented on src/guide/essentials/application.md
> +这使得 `TodoDeleteButton` 在应用的任何地方都是可用的。我们会在指引的后续章节中讨论关于组件和其他资源的注册。你也可以在 [API 参考](/api/application) 中浏览应用实例 API 的完整列表。
```suggestion
这使得 `TodoDeleteButton` 在应用的任何地方都是可用的。我们会在指引的后续章节中讨论关于组件和其他资源的注册。你也可以在 [API 参考](/api/application)中浏览应用实例 API 的完整列表。
```

2022-02-02 04:20 UTC, Jinjiang commented on src/guide/essentials/application.md
> +你不必再受限于一个页面只能拥有一个应用实例。`createApp` API 允许多个 Vue 应用共存于同一个页面上，它们每一个都是隔离的，有自己的配置和全局资源。
```suggestion
你不必再受限于一个页面只能拥有一个应用实例。`createApp` API 允许多个 Vue 应用共存于同一个页面上，而且每个应用都拥有自己的用于配置和全局资源的作用域。
```

2022-02-03 10:49 UTC, wxsms commented on src/guide/essentials/application.md
> +该方法接收一个“容器”参数，可以是一个实际的 DOM 元素或是一个 CSS 选择器字符串：
貌似目前原文是有折行的哦

2022-02-05 03:38 UTC, Jinjiang commented on src/guide/essentials/application.md
> +该方法接收一个“容器”参数，可以是一个实际的 DOM 元素或是一个 CSS 选择器字符串：
了解了。但这样会有个问题……就是这两行文本之间在渲染的时候会多出一个空格来。不然我们把两行合并，然后下面多空一行好了。

2022-02-06 04:44 UTC, KimYangOfCat commented on src/guide/essentials/application.md
> +该方法接收一个“容器”参数，可以是一个实际的 DOM 元素或是一个 CSS 选择器字符串：
@Jinjiang  也可以， @wxsms 你的意见呢？

2022-02-06 07:11 UTC, Jinjiang commented on src/guide/essentials/application.md
> +该方法接收一个“容器”参数，可以是一个实际的 DOM 元素或是一个 CSS 选择器字符串：
我个人觉得可以。
英文应该是不必要在这里折行的，我之前在别的文件里也遇到过，可能原版作者写的时候相对随意一些，毕竟在英文句子的标点符号后面折行不影响渲染结果。
另外如果我们不是特别紧急一定要和英文版行号严格对齐，那就不必刻意多空一行了

2022-02-06 09:59 UTC, KimYangOfCat commented on src/guide/essentials/application.md
> +该方法接收一个“容器”参数，可以是一个实际的 DOM 元素或是一个 CSS 选择器字符串：
@Jinjiang 是的，那我去给英文仓库提个PR，修改一下，后续同步后就删除这里的折行

2022-02-07 03:17 UTC, KimYangOfCat commented on src/guide/essentials/application.md
> +该方法接收一个“容器”参数，可以是一个实际的 DOM 元素或是一个 CSS 选择器字符串：
@wxsms @Jinjiang 英文 PR已被合并，此处是否还需要修改？还是等下次同步英文内容时再做修改？

2022-02-07 06:23 UTC, wxsms commented on src/guide/essentials/application.md
> +该方法接收一个“容器”参数，可以是一个实际的 DOM 元素或是一个 CSS 选择器字符串：
> @wxsms @Jinjiang 英文 PR已被合并，此处是否还需要修改？还是等下次同步英文内容时再做修改？

建议同步修改，谢谢！

2022-02-07 07:04 UTC, wxsms commented on src/guide/essentials/application.md
> +该方法接收一个“容器”参数，可以是一个实际的 DOM 元素或是一个 CSS 选择器字符串：
是的

2022-02-07 13:30 UTC, KimYangOfCat commented on src/guide/essentials/application.md
> +该方法接收一个“容器”参数，可以是一个实际的 DOM 元素或是一个 CSS 选择器字符串：
@Jinjiang @wxsms 已完成修改

2022-02-08 02:27 UTC, merged