docs(computed): review src\guide\essentials\computed.md
vuejs-translations/docs-zh-cn pull request #22
Opened 2022-01-18 14:04 UTC by KimYangOfCat

2022-01-19 16:54 UTC, Jinjiang commented
发现有 conflict 👀

2022-01-20 03:16 UTC, KimYangOfCat commented
@Jinjiang 已解决

2022-01-22 11:35 UTC, watonyweng commented on src/guide/essentials/computed.md
> +也可参考: [为计算属性标注类型](/guide/typescript/composition-api.html#typing-computed) <sup class="vt-badge ts">TS</sup>
```suggestion
参考: [为计算属性标注类型](/guide/typescript/composition-api.html#typing-computed) <sup class="vt-badge ts">TS</sup>
```

2022-01-22 11:45 UTC, watonyweng commented on src/guide/essentials/computed.md
> +一个计算属性会自动追踪响应式依赖。Vue 会意识到 `this.publishedBooksMessage` 依赖于 `this.author.books`，所以当 `this.author.books` 改变时，任何绑定 `vm.publishedBooksMessage` 都将同时更新。
```suggestion
Vue 的计算属性会自动追踪响应式依赖。它会检测到 `this.publishedBooksMessage` 依赖于 `this.author.books`，所以当 `this.author.books` 改变时，任何绑定 `vm.publishedBooksMessage` 都会同时更新。
```

2022-01-23 04:29 UTC, wxsms requested changes

2022-01-23 04:29 UTC, wxsms commented on src/guide/essentials/computed.md
> +模板中的表达式虽然方便，但也只能用来做简单的操作。如果在模板中写太多逻辑，会让使其变得复杂，难以维护。比如我们有这样一个对象，其中有一个嵌套的数组：
```suggestion
模板中的表达式虽然方便，但也只能用来做简单的操作。如果在模板中写太多逻辑，会让使其变得复杂，难以维护。比如说，我们有这样一个包含嵌套数组的对象：
```

2022-01-23 04:29 UTC, wxsms commented on src/guide/essentials/computed.md
> +这里的模板看起来有些复杂。我们必须认真看好一会儿才能明白它依赖于 `author.books` 做计算。更重要的是，如果这样的计算在模板中不只一次，我们可能不想写重复的代码。
```suggestion
这里的模板看起来有些复杂。我们必须认真看好一会儿才能明白它的计算依赖于 `author.books`。更重要的是，如果需要在模板中包含不止一次这样的计算，我们可能不想写重复的代码。
```

2022-01-23 04:29 UTC, wxsms commented on src/guide/essentials/computed.md
>  在模板中使用计算属性和一般的属性并无二致。Vue 会意识到 `this.publishedBooksMessage` 依赖于 `this.author.books`，所以当 `this.author.books` 改变时，任何绑定 `vm.publishedBooksMessage` 都将同时更新。
```suggestion
在模板中使用计算属性的方式和一般的 property 并无二致。Vue 会检测到 `this.publishedBooksMessage` 依赖于 `this.author.books`，所以当 `this.author.books` 改变时，任何依赖于 `vm.publishedBooksMessage` 的绑定都将同时更新。
```

2022-01-23 04:29 UTC, wxsms commented on src/guide/essentials/computed.md
> +我们在这里定义了一个计算属性 `publishedBooksMessage`。`computed()` 方法期望接收一个 getter 函数，返回值为一个 **计算 ref**。和其他一般的 ref 类似，你可以通过 `publishedBooksMessage.value` 访问到计算结果。计算 ref 也会在模板中自动解包因此在模板的表达式中无需 `.value`。
```suggestion
我们在这里定义了一个计算属性 `publishedBooksMessage`。`computed()` 方法期望接收一个 getter 函数，返回值为一个**计算 ref**。和其他一般的 ref 类似，你可以通过 `publishedBooksMessage.value` 访问计算结果。计算 ref 也会在模板中自动解包，因此在模板表达式中引用时无需添加 `.value`。
```

2022-01-23 04:29 UTC, wxsms commented on src/guide/essentials/computed.md
> +一个计算属性会自动追踪响应式依赖。Vue 会意识到 `this.publishedBooksMessage` 依赖于 `this.author.books`，所以当 `this.author.books` 改变时，任何绑定 `vm.publishedBooksMessage` 都将同时更新。
```suggestion
计算属性会自动追踪其响应式依赖。Vue 会检测到 `this.publishedBooksMessage` 依赖于 `this.author.books`，所以当 `this.author.books` 改变时，任何依赖于 `vm.publishedBooksMessage` 的绑定都将同时更新。
```

2022-01-23 04:29 UTC, wxsms commented on src/guide/essentials/computed.md
> +因此我们推荐使用 **计算属性** 来描述依赖响应式状态的复杂逻辑。这是重构后的示例：
```suggestion
因此我们推荐使用**计算属性**来描述依赖响应式状态的复杂逻辑。这是重构后的示例：
```

2022-01-23 04:29 UTC, wxsms commented on src/guide/essentials/computed.md
> +我们在这里定义了一个计算属性 `publishedBooksMessage`。`computed()` 方法期望接收一个 getter 函数，返回值为一个 **计算 ref**。和其他一般的 ref 类似，你可以通过 `publishedBooksMessage.value` 访问到计算结果。计算 ref 也会在模板中自动解包因此在模板的表达式中无需 `.value`。
关于 computed ref 是否翻译为计算 ref，是否需要再讨论一下？

2022-01-23 08:45 UTC, KimYangOfCat commented on src/guide/essentials/computed.md
> +也可参考: [为计算属性标注类型](/guide/typescript/composition-api.html#typing-computed) <sup class="vt-badge ts">TS</sup>
这里加上“也可”二字，会让上下文阅读起来更流畅，与英文愿意也更符合，所暂时不采纳这个意见，抱歉

2022-01-23 08:48 UTC, KimYangOfCat commented on src/guide/essentials/computed.md
> +这里的模板看起来有些复杂。我们必须认真看好一会儿才能明白它依赖于 `author.books` 做计算。更重要的是，如果这样的计算在模板中不只一次，我们可能不想写重复的代码。
> 如果需要在模板中包含不止一次这样的计算

改为：
如果在模板中需要不止一次这样的计算

会不会好点儿？

2022-01-23 08:56 UTC, KimYangOfCat commented on src/guide/essentials/computed.md
> +我们在这里定义了一个计算属性 `publishedBooksMessage`。`computed()` 方法期望接收一个 getter 函数，返回值为一个 **计算 ref**。和其他一般的 ref 类似，你可以通过 `publishedBooksMessage.value` 访问到计算结果。计算 ref 也会在模板中自动解包因此在模板的表达式中无需 `.value`。
虽然我认为应该不会有分歧，但还是有必要讨论一下，这也算是Vue中的一个术语，讨论然后整合进术语约定最好。已开 issue #40

2022-01-23 08:58 UTC, wxsms commented on src/guide/essentials/computed.md
> +这里的模板看起来有些复杂。我们必须认真看好一会儿才能明白它依赖于 `author.books` 做计算。更重要的是，如果这样的计算在模板中不只一次，我们可能不想写重复的代码。
> 如果在模板中需要不止一次这样的计算

我觉得ok

2022-01-23 08:58 UTC, KimYangOfCat commented on src/guide/essentials/computed.md
> +一个计算属性会自动追踪响应式依赖。Vue 会意识到 `this.publishedBooksMessage` 依赖于 `this.author.books`，所以当 `this.author.books` 改变时，任何绑定 `vm.publishedBooksMessage` 都将同时更新。
@watonyweng 基于你的意见作了很好的补充，我就先行合并他的啦，多谢

2022-01-24 12:40 UTC, KimYangOfCat commented on src/guide/essentials/computed.md
> +一个计算属性会自动追踪响应式依赖。Vue 会意识到 `this.publishedBooksMessage` 依赖于 `this.author.books`，所以当 `this.author.books` 改变时，任何绑定 `vm.publishedBooksMessage` 都将同时更新。
我已将这个suggestion手动更新到了当前PR中，但是由于你的review是requested，导致当前PR还无法合并，请问，我应该如何解决这个问题？
![image](https://user-images.githubusercontent.com/32960305/150784580-daf67b5f-3be7-4ab5-bdf8-f55ace5a2b1b.png)

2022-01-24 12:55 UTC, wxsms approved these changes

2022-01-24 12:55 UTC, wxsms commented on src/guide/essentials/computed.md
> +一个计算属性会自动追踪响应式依赖。Vue 会意识到 `this.publishedBooksMessage` 依赖于 `this.author.books`，所以当 `this.author.books` 改变时，任何绑定 `vm.publishedBooksMessage` 都将同时更新。
已approve

2022-01-24 12:57 UTC, KimYangOfCat commented on src/guide/essentials/computed.md
> +一个计算属性会自动追踪响应式依赖。Vue 会意识到 `this.publishedBooksMessage` 依赖于 `this.author.books`，所以当 `this.author.books` 改变时，任何绑定 `vm.publishedBooksMessage` 都将同时更新。
谢谢

2022-01-26 08:06 UTC, wxsms commented on src/guide/essentials/computed.md
>  <span>{{ author.books.length > 0 ? 'Yes' : 'No' }}</span>
L45

```
<p>Has published books:</p>
```

2022-01-26 08:06 UTC, wxsms commented on src/guide/essentials/computed.md
L70

```
    //一个计算属性的 getter
```

L80/L118

```
<p>Has published books:</p>
```

2022-01-26 08:07 UTC, wxsms commented
增加了一些 review，因为不在你的 changes 覆盖范围内所以用不了 code sugguestion，麻烦再确认一下。

2022-01-28 14:00 UTC, watonyweng commented on src/guide/essentials/computed.md
> +也可参考: [为计算属性标注类型](/guide/typescript/composition-api.html#typing-computed) <sup class="vt-badge ts">TS</sup>
@KimYangOfCat 客气啦，我只是个人意见

2022-01-28 14:46 UTC, KimYangOfCat commented
@wxsms 已更新

2022-01-30 03:42 UTC, Jinjiang commented on src/guide/essentials/computed.md
> +    //一个计算属性的 getter
```suggestion
    // 一个计算属性的 getter
```

2022-01-30 03:43 UTC, Jinjiang commented
只有一个小地方需要改动，不介意的话我直接提交合并好了

2022-01-30 03:43 UTC, merged

2022-01-31 01:53 UTC, KimYangOfCat commented
@Jinjiang 感谢帮助改正