docs(api): translation src/api/sfc-css-features.md completed
vuejs-translations/docs-zh-cn pull request #265
Opened 2022-04-15 04:34 UTC by jiang-24-gdufs

close #263

2022-04-25 07:01 UTC, KiritaniAyaka requested changes

2022-04-25 07:01 UTC, KiritaniAyaka commented on src/api/sfc-css-features.md
> +// 命名, 返回 <style module="classes"> 的 class
```suggestion
// 具名情况下, 返回 <style module="classes"> 的 class 
```

2022-04-26 08:08 UTC, wxsms commented on src/api/sfc-css-features.md
> +- **作用域样式并没有消除对 class 的需求**。由于浏览器渲染各种各样 CSS 选择器的方式，`p { color: red }` 结合作用域样式使用时会慢很多倍 (即，当与 attribute 选择器组合的时候)。如果你使用 class 或者 id 来替代，例如 `.example { color: red }`，那你几乎就可以避免性能的损失。
```suggestion
- **作用域样式并没有消除对 class 的需求**。由于浏览器渲染各种各样 CSS 选择器的方式，`p { color: red }` 结合作用域样式使用时（即当与 attribute 选择器组合的时候）会慢很多倍。如果你使用 class 或者 id 来替代，例如 `.example { color: red }`，那你几乎就可以避免性能的损失。
```

2022-04-26 08:08 UTC, wxsms commented on src/api/sfc-css-features.md
> +- **小心递归组件中的后代选择器**。对于一个使用了 `.a .b` 选择器的样式规则来说，如果匹配到 `.a` 的元素包含了一个递归的子组件，那么所有的在那个子组件中的 `.b` 都会匹配到这条样式规则。
```suggestion
- **小心递归组件中的后代选择器**！对于一个使用了 `.a .b` 选择器的样式规则来说，如果匹配到 `.a` 的元素包含了一个递归的子组件，那么所有的在那个子组件中的 `.b` 都会匹配到这条样式规则。
```

2022-04-26 08:08 UTC, wxsms commented on src/api/sfc-css-features.md
> +一个 `<style module>` 标签会被编译为 [CSS Modules](https://github.com/css-modules/css-modules) 并且将生成的 CSS class 作为 `$style` 对象的键值暴露给组件：
```suggestion
一个 `<style module>` 标签会被编译为 [CSS Modules](https://github.com/css-modules/css-modules) 并且将生成的 CSS class 作为 `$style` 对象暴露给组件：
```

2022-04-26 08:08 UTC, wxsms commented on src/api/sfc-css-features.md
> +对 class 做 hash 计算以避免冲突，实现了和作用域 CSS 一样将 CSS 仅作用于当前组件的效果。
```suggestion
得出的 class 将被哈希化以避免冲突，实现了同样的将 CSS 仅作用于当前组件的效果。
```

2022-04-26 08:08 UTC, wxsms commented on src/api/sfc-css-features.md
> +你可以通过给 module attribute 一个值来自定义注入的 class 对象的 property 键：
```suggestion
你可以通过给 `module` attribute 一个值来自定义注入 class 对象的 property 键：
```

2022-04-26 08:08 UTC, wxsms commented on src/api/sfc-css-features.md
> +可以通过 `useCssModule` API 在 `setup()` 和 `<script setup>` 中访问注入的 class 。对于使用了自定义注入名称的 `<style module>` 块，`useCssModule` 接收一个匹配的 `module` attribute 值作为第一个参数。
```suggestion
可以通过 `useCssModule` API 在 `setup()` 和 `<script setup>` 中访问注入的 class。对于使用了自定义注入名称的 `<style module>` 块，`useCssModule` 接收一个匹配的 `module` attribute 值作为第一个参数：
```

2022-04-26 08:08 UTC, wxsms commented on src/api/sfc-css-features.md
> +单文件组件 `<style>` 标签支持使用 `v-bind` CSS 函数将 CSS 的值链接到动态组件的状态：
```suggestion
单文件组件的 `<style>` 标签支持使用 `v-bind` CSS 函数将 CSS 的值链接到动态的组件状态：
```

2022-04-26 08:08 UTC, wxsms commented on src/api/sfc-css-features.md
> +这个语法同样也适用于 [`<script setup>`](./sfc-script-setup)，且支持 JavaScript 表达式 (需要用引号包裹起来)
```suggestion
这个语法同样也适用于 [`<script setup>`](./sfc-script-setup)，且支持 JavaScript 表达式（需要用引号包裹起来）：
```

2022-04-26 08:08 UTC, wxsms commented on src/api/sfc-css-features.md
> +实际的值会被编译成 hash 的 CSS 自定义 property，CSS 本身仍然是静态的。自定义 property 会通过内联样式的方式应用到组件的根元素上，并且在源值变更的时候响应式更新。
```suggestion
实际的值会被编译成哈希化的 CSS 自定义 property，因此 CSS 本身仍然是静态的。自定义 property 会通过内联样式的方式应用到组件的根元素上，并且在源值变更的时候响应式地更新。
```

2022-04-26 08:14 UTC, merged