Translated all the practical examples
vuejs-translations/docs-zh-cn pull request #403
Opened 2022-05-27 13:39 UTC by Jinjiang

- markdown
- fetching-data
- grid
- tree
- svg
- modal
- list-transition
- todomvc

2022-05-27 13:56 UTC, Justineo commented on src/examples/src/fetching-data/App/options.js
> +    // 在初始化的时候进行抓取
读取？

2022-05-27 14:01 UTC, Justineo requested changes

2022-05-27 14:01 UTC, Justineo commented on src/examples/src/tree/TreeItem/composition.js
> +  name: 'TreeItem', // 在自引用的时候是必须的
```suggestion
  name: 'TreeItem', // 在引用自身的时候是必须的
```

2022-05-27 14:01 UTC, Justineo commented on src/examples/src/tree/TreeItem/options.js
> +  name: 'TreeItem', // 在自引用的时候是必须的
```suggestion
  name: 'TreeItem', // 在引用自身的时候是必须的
```

2022-05-27 15:47 UTC, Jinjiang commented on src/examples/src/fetching-data/App/options.js
> +    // 在初始化的时候进行抓取
感觉读取像是个普通的本地操作，fetch 是产生网络请求的。有别的建议吗？

2022-05-28 08:31 UTC, wxsms commented on src/examples/src/fetching-data/App/options.js
> +    // 在初始化的时候进行抓取
建议“获取”

2022-05-29 05:20 UTC, Justineo commented on src/examples/src/fetching-data/App/options.js
> +    // 在初始化的时候进行抓取
感觉“获取”好一些。@Jinjiang 觉得呢？（下面也有一个地方有 fetch）

2022-06-01 14:40 UTC, Jinjiang commented on src/examples/src/fetching-data/App/options.js
> +    // 在初始化的时候进行抓取
```suggestion
    // 在初始化的时候进行获取
```

2022-06-01 14:40 UTC, Jinjiang commented on src/examples/src/fetching-data/App/options.js
> +    // 当 currentBranch 改变时重新抓取
```suggestion
    // 当 currentBranch 改变时重新获取
```

2022-06-03 16:40 UTC, Justineo approved these changes

2022-06-03 16:41 UTC, merged