review: sfc-script-setup.md
vuejs-translations/docs-zh-cn pull request #404
Opened 2022-05-28 03:58 UTC by wxsms

## Description of Problem

close #337

2022-05-28 06:40 UTC, watonyweng requested changes

2022-05-28 06:40 UTC, watonyweng commented on src/api/sfc-script-setup.md
>  ## `defineExpose` {#defineexpose}
## `defineExpose` {#define-expose}

2022-05-28 06:41 UTC, watonyweng approved these changes

2022-05-28 08:29 UTC, wxsms commented on src/api/sfc-script-setup.md
>  ## `defineExpose` {#defineexpose}
原文锚点为 #defineexpose，此处应该是正确的

2022-05-30 02:14 UTC, veaba approved these changes

2022-05-30 02:14 UTC, merged