Sync #da406ac
vuejs-translations/docs-zh-cn pull request #460
Opened 2022-07-07 06:29 UTC by wxsms

## Description of Problem

https://github.com/vuejs-translations/docs-zh-cn/compare/233c074...da406ac

## Proposed Solution

## Additional Information

2022-07-07 06:33 UTC, wxsms commented on src/guide/built-ins/transition.md
> +/* ... other necessary CSS omitted */
```suggestion
/* ... 省略了其他必要的 CSS */
```

2022-07-07 06:33 UTC, wxsms commented on src/guide/components/async.md
> +<!-- TODO: translation --> As with normal components, async components can be [registered globally](/guide/components/registration.html#global-registration) using `app.component()`:
```suggestion
与普通组件一样，异步组件可以使用 `app.component()` [全局注册](/guide/components/registration.html#global-registration)：
```

2022-07-18 07:01 UTC, Justineo requested changes

2022-07-20 11:48 UTC, Justineo approved these changes

2022-07-20 11:49 UTC, merged