Format articles by zhlint
vuejs-translations/docs-zh-cn pull request #502
Opened 2022-08-12 09:17 UTC by Jinjiang

- format all the articles
- upgrade `zhlint` to the latest version
- enlarge the scope of `pnpm zhlint`

2022-08-13 03:37 UTC, veaba commented on src/api/application.md
> +如果同时传递一个组件名字符串及其定义，则注册一个全局组件；如果只传递一个名字，则会返回用该名字注册组件 (如果存在的话)。
这里的括号都是半角了吗，这 wiki 似乎有冲突

2022-08-13 04:06 UTC, Jinjiang commented on src/api/application.md
> +如果同时传递一个组件名字符串及其定义，则注册一个全局组件；如果只传递一个名字，则会返回用该名字注册组件 (如果存在的话)。
“括号统一使用半角括号 ()”

2022-08-14 12:31 UTC, Justineo requested changes

2022-08-14 12:31 UTC, Justineo commented on src/guide/essentials/component-basics.md
> +在父组件中，我们可以添加一个 `postFontSize` <span class="options-api">数据属性</span><span class="composition-api">ref </span>来实现这个效果：
这个是不是有问题

2022-08-14 12:31 UTC, Justineo commented on src/guide/essentials/forms.md
> +`v-model` 会忽略任何表单元素上初始的 `value`、`checked` 或 `selected` attribute。它将始终将当前绑定的 JavaScript 状态视为数据的正确来源。你应该在 JavaScript 中使用<span class="options-api"> `data` 选项</span><span class="composition-api">响应式系统的 A
同上

2022-08-14 16:13 UTC, Jinjiang commented on src/guide/essentials/component-basics.md
> +在父组件中，我们可以添加一个 `postFontSize` <span class="options-api">数据属性</span><span class="composition-api">ref </span>来实现这个效果：
这样的话在两种模式下分别是：

```md
在父组件中，我们可以添加一个 `postFontSize` 数据属性来实现这个效果：
```

和

```md
在父组件中，我们可以添加一个 `postFontSize` ref 来实现这个效果：
```

空格的使用刚好都对

2022-08-14 16:14 UTC, Jinjiang commented on src/guide/essentials/forms.md
> +`v-model` 会忽略任何表单元素上初始的 `value`、`checked` 或 `selected` attribute。它将始终将当前绑定的 JavaScript 状态视为数据的正确来源。你应该在 JavaScript 中使用<span class="options-api"> `data` 选项</span><span class="composition-api">响应式系统的 A
```md
`v-model` 会忽略任何表单元素上初始的 `value`、`checked` 或 `selected` attribute。它将始终将当前绑定的 JavaScript 状态视为数据的正确来源。你应该在 JavaScript 中使用 `data` 选项来声明该初始值。
```

和

```md
`v-model` 会忽略任何表单元素上初始的 `value`、`checked` 或 `selected` attribute。它将始终将当前绑定的 JavaScript 状态视为数据的正确来源。你应该在 JavaScript 中使用响应式系统的 API 来声明该初始值。
```

2022-08-16 03:20 UTC, wxsms approved these changes

2022-08-16 03:23 UTC, Justineo approved these changes

2022-08-16 03:24 UTC, merged