chore: add issue template
vuejs-translations/docs-zh-cn pull request #507
Opened 2022-08-16 03:01 UTC by wxsms

## Description of Problem

增加 isssue template

[预览地址](https://github.com/wxsms/vuejs-docs-zh-cn/issues/new?assignees=&labels=&template=bug_report.yaml&title=%5BBug%5D%3A+)

2022-08-16 03:22 UTC, Justineo requested changes

2022-08-16 03:22 UTC, Justineo commented on .github/ISSUE_TEMPLATE/bug_report.yaml
> +title: "[Bug]: "
这个是不是默认别填了

2022-08-16 03:22 UTC, Justineo commented on .github/ISSUE_TEMPLATE/bug_report.yaml
> +        3. 其它与本仓库直接相关的问题，如译法讨论、流程优化等；
```suggestion
        3. 其他与本仓库直接相关的问题，如译法讨论、流程优化等。
```

2022-08-16 03:22 UTC, Justineo commented on .github/ISSUE_TEMPLATE/bug_report.yaml
> +        1. Vue 使用问题答疑；
```suggestion
        请注意，Vue (包括相关的核心库 Vue Router、Pinia 等) 在使用上的答疑**不在**本仓库的处理范围内，相关 issue 将可能被直接关闭。此类问题请在我们的[论坛](https://forum.vuejs.org/c/chinese/7)、[Discord](https://discord.com/channels/325477692906536972/325654285255704578) 或 [StackOverflow](https://stackoverflow.com/tags/vue.js) 上发帖求助。
```

2022-08-16 03:22 UTC, Justineo commented on .github/ISSUE_TEMPLATE/bug_report.yaml
> +        - 其它
```suggestion
        - 其他
```

2022-08-16 03:22 UTC, Justineo commented on .github/ISSUE_TEMPLATE/bug_report.yaml
> +        1. Vue 使用问题答疑；
声明不处理，然后也引导一下吧

2022-08-16 03:22 UTC, Justineo commented on .github/ISSUE_TEMPLATE/bug_report.yaml
> +        本仓库是 Vue 3 文档中文翻译站 [cn.vuejs.org](https://cn.vuejs.org/)。这里仅受理以下类型的问题：
```suggestion
        本仓库是 Vue 3 文档中文翻译站 [cn.vuejs.org](https://cn.vuejs.org/)。这里仅处理以下类型的问题：
```

感觉这样语气友好一点

2022-08-16 03:28 UTC, wxsms commented on .github/ISSUE_TEMPLATE/bug_report.yaml
> +title: "[Bug]: "
ok

2022-08-16 03:34 UTC, Justineo approved these changes

2022-08-16 03:34 UTC, Justineo commented
我觉得没问题，@Jinjiang @veaba @ShenQingchuan 看看？

2022-08-16 07:42 UTC, veaba commented
可能是我的错觉，突然有点“太长不看”的错觉。:smile:

我试着出一个版本措辞，看看效果。

2022-08-16 08:11 UTC, veaba reviewed
尝试口语化。

2022-08-16 08:11 UTC, veaba commented on .github/ISSUE_TEMPLATE/bug_report.yaml
> +        若问题涉及文档内容以及文档中的代码块，请先确认该问题是中文仓库本身的问题，还是来自于[英文仓库](https://github.com/vuejs/docs)的问题。如果是来自英文仓库的问题，请向英文仓库提出 issue，本仓库会定期同步来自英文仓库的改动。
```suggestion
        请区分`中文仓库`还是[`英文仓库`](https://github.com/vuejs/docs)的问题。是英文，请前往 `vuejs/docs` ，我们会定期同步。
```

2022-08-16 08:11 UTC, veaba commented on .github/ISSUE_TEMPLATE/bug_report.yaml
> +        请注意，Vue (包括相关的核心库 Vue Router、Pinia 等) 在使用上的答疑**不在**本仓库的处理范围内，相关 issue 将可能被直接关闭。此类问题请在我们的[论坛](https://forum.vuejs.org/c/chinese/7)、[Discord 聊天室](https://chat.vuejs.org/) 或 [StackOverflow](http
```suggestion
        我们不处理 Vue 周边(包括相关的核心库 Vue Router、Pinia 等) 的**使用**问题。
        
        请前往：[论坛](https://forum.vuejs.org/c/chinese/7)、[Discord 聊天室](https://chat.vuejs.org/) 或 [StackOverflow](https://stackoverflow.com/tags/vue.js) 上发帖求助。
```

2022-08-16 08:11 UTC, veaba commented on .github/ISSUE_TEMPLATE/bug_report.yaml
> +      description: 请描述你所遇到的问题，如果存在复现路径请一并描述。
```suggestion
      description: 请描述问题，**截图+有效链接更佳**。
```

2022-08-16 08:11 UTC, veaba commented on .github/ISSUE_TEMPLATE/bug_report.yaml
> +      description: 请认真阅读以上说明后，勾选本字段。
```suggestion
      description: 以上已阅！请勾选。
```

2022-08-16 15:32 UTC, Jinjiang commented
一些个人建议：

1. 问题类型建议单独加入“网络环境和本地化”这一项，比如网站慢或打不开之类的报告，或那些内容英文版里有但不适合直接放在中文版里等。
2. 英文文档同步似乎不太需要发 issue，直接发 PR 就可以，感觉可以省掉。
3. 建议加入几个必须勾选的字段：
    - 我确定这是官方版本 cn.vuejs.org 的 issue，而不是其他非官方翻译版本
    - 我确定这是翻译问题，而不是英文原文的问题 (英文原文的问题请移步至英文文档的仓库讨论)
    - 我确定这不是 Vue.js 使用方面的问题 (此类问题请在我们的[论坛](https://forum.vuejs.org/c/chinese/7)、[Discord 聊天室](https://chat.vuejs.org/) 或 [StackOverflow](https://stackoverflow.com/tags/vue.js) 上发帖求助)

2022-08-17 01:41 UTC, wxsms commented on .github/ISSUE_TEMPLATE/bug_report.yaml
> +description: 报告本站点相关的问题。请认真阅读并填写，否则 issue 将可能被直接关闭。
这里主要是对应创建 issue 时的提示，见：https://github.com/wxsms/vuejs-docs-zh-cn/issues/new/choose
我觉得还是说清楚好一些...

2022-08-17 01:42 UTC, wxsms commented on .github/ISSUE_TEMPLATE/bug_report.yaml
> +        报告本站点相关的问题。请认真阅读并填写，否则 issue 将可能被直接关闭。
这一句貌似可以删掉，跟进入时的提示重复了，我删掉吧。

2022-08-17 02:03 UTC, wxsms commented
> 可能是我的错觉，突然有点“太长不看”的错觉。😄
> 
> 我试着出一个版本措辞，看看效果。

@veaba “太长不看”的问题，按照 @Jinjiang 的建议，在勾选处以更简短的方式描述了一遍，并作为必选项。这样是否有所改善？

2022-08-17 02:06 UTC, wxsms commented on .github/ISSUE_TEMPLATE/bug_report.yaml
> +        3. 其他与本仓库直接相关的问题，如译法讨论、流程优化等。
此处貌似缺少了部分代码...?

2022-08-17 03:34 UTC, Jinjiang commented on .github/ISSUE_TEMPLATE/bug_report.yaml
> +description: 报告本站点相关的问题。请认真阅读并填写，否则 issue 将可能被直接关闭。
> 这里主要是对应创建 issue 时的提示，见：https://github.com/wxsms/vuejs-docs-zh-cn/issues/new/choose 我觉得还是说清楚好一些...

认同，觉得目前的说法是 OK 的

2022-08-17 03:34 UTC, Jinjiang commented on .github/ISSUE_TEMPLATE/bug_report.yaml
> +        若问题涉及文档内容以及文档中的代码块，请先确认该问题是中文仓库本身的问题，还是来自于[英文仓库](https://github.com/vuejs/docs)的问题。如果是来自英文仓库的问题，请向英文仓库提出 issue，本仓库会定期同步来自英文仓库的改动。
感觉有了新增加的两个勾选项，这两句可以省略了

2022-08-17 03:34 UTC, Jinjiang commented on .github/ISSUE_TEMPLATE/bug_report.yaml
> +        请注意，Vue (包括相关的核心库 Vue Router、Pinia 等) 在使用上的答疑**不在**本仓库的处理范围内，相关 issue 将可能被直接关闭。此类问题请在我们的[论坛](https://forum.vuejs.org/c/chinese/7)、[Discord 聊天室](https://chat.vuejs.org/) 或 [StackOverflow](http
同上

2022-08-17 03:34 UTC, Jinjiang commented on .github/ISSUE_TEMPLATE/bug_report.yaml
> +        - label: 我确定这是翻译问题，而不是英文原文的问题 (英文原文的问题请移步至[英文文档仓库](https://github.com/vuejs/docs)讨论)
```suggestion
        - label: 我确定这是翻译问题，而不是英文原文的问题 (英文原文的问题请移步至[英文文档仓库](https://github.com/vuejs/docs)讨论，相关结论我们会定期从英文版同步)
```

2022-08-17 05:11 UTC, veaba commented on .github/ISSUE_TEMPLATE/bug_report.yaml
> +        3. 其他与本仓库直接相关的问题，如译法讨论、流程优化等。
这个不太确认，template  能不能渲染 mermaid。

2022-08-17 05:22 UTC, veaba commented
这边的建议是，尽量重点突出、长话短说，粗暴点也没关系。

> 用户可能想花上几分钟时间仔细品读……，:smile:

另外有两个情况，可以讨论一下：

1、这边也有英文用户过来发 issue（比较少），对他们可能不太友好（添加双语版？:smile:）。

2、close 情况，应该是两个事情：
   - 英文讨论来错地方，应该去英文库，issue 会被 close
   - Vue 周边用法讨论，issue 被 close

2022-08-17 09:57 UTC, Jinjiang commented on .github/ISSUE_TEMPLATE/bug_report.yaml
> +        3. 其他与本仓库直接相关的问题，如译法讨论、流程优化等。
我觉得必要性不大了，流程并不复杂，不需要图表来辅助理解

2022-08-17 10:00 UTC, Jinjiang commented
> 这边的建议是，尽量重点突出、长话短说，粗暴点也没关系。
> 
> > 用户可能想花上几分钟时间仔细品读……，😄
> 
> 另外有两个情况，可以讨论一下：
> 
> 1、这边也有英文用户过来发 issue（比较少），对他们可能不太友好（添加双语版？😄）。
> 
> 2、close 情况，应该是两个事情：
> 
> * 英文讨论来错地方，应该去英文库，issue 会被 close
> * Vue 周边用法讨论，issue 被 close

问题 1：依赖可以 open a blank issue，而且是英文提示 https://github.com/wxsms/vuejs-docs-zh-cn/issues/new/choose
问题 2：这两种问题目前的模板应该都涵盖了

2022-08-17 10:01 UTC, merged