Sync #34b7682
vuejs-translations/docs-zh-cn pull request #517
Opened 2022-08-24 01:51 UTC by wxsms

## Description of Problem

https://github.com/vuejs/docs/compare/c9e1ad4...34b768211f810eb04751e22f0c75c4ceb0e14f09

2022-08-24 04:35 UTC, Justineo requested changes

2022-08-24 06:20 UTC, wxsms commented on src/about/faq.md
> +Vue 2 在 2022 年 6 月发布了最后一个小版本 (2.7)。目前 Vue 2 已经进入维护模式：它将不再提供新特性，但从 2.7 的发布日期开始的 18 个月内，它将继续针对重大错误修复和安全更新进行发布。这意味着**到 2023 年年底，Vue 2 将正式停止维护并到达生命的尽头**。我们相信这将为大多数的生态系统提供了足够长的时间来迁移到 Vue 3。然而，我们也理解可能会有无法在
> “到达生命的尽头”是不是用“进入完结状态”这样的表述更好一点？

“停止维护并结束生命周期”如何？

https://zh.wikipedia.org/wiki/%E7%94%A2%E5%93%81%E5%A3%BD%E5%91%BD%E7%B5%90%E6%9D%9F

2022-08-27 05:04 UTC, Jinjiang commented on src/about/faq.md
> +Vue 2 在 2022 年 6 月发布了最后一个小版本 (2.7)。目前 Vue 2 已经进入维护模式：它将不再提供新特性，但从 2.7 的发布日期开始的 18 个月内，它将继续针对重大错误修复和安全更新进行发布。这意味着**到 2023 年年底，Vue 2 将正式停止维护并到达生命的尽头**。我们相信这将为大多数的生态系统提供了足够长的时间来迁移到 Vue 3。然而，我们也理解可能会有无法在
Node 中文版文档把 end-of-life 译为了“截止维护日期”我觉得可以借鉴。

https://nodejs.org/zh-cn/about/releases/

2022-08-27 05:11 UTC, Jinjiang commented on .vitepress/theme/components/Home.vue
> +        <!-- <span v-if="description">{{ description }}</span> -->
L268-L270

```
  #special-sponsor span {
    margin: 0;
  }
```

漏掉了

2022-08-27 05:11 UTC, Jinjiang commented on src/guide/best-practices/performance.md
> +## Update Optimizations
```suggestion
## 更新优化 {#update-optimizations}
```

2022-08-29 01:27 UTC, wxsms commented on .vitepress/theme/components/Home.vue
> +        <!-- <span v-if="description">{{ description }}</span> -->
> L268-L270
> 
> ```
>   #special-sponsor span {
>     margin: 0;
>   }
> ```
> 
> 漏掉了

这段已经在 c5fa83c 中覆盖

2022-08-29 01:31 UTC, wxsms commented on src/about/faq.md
> +Vue 2 在 2022 年 6 月发布了最后一个小版本 (2.7)。目前 Vue 2 已经进入维护模式：它将不再提供新特性，但从 2.7 的发布日期开始的 18 个月内，它将继续针对重大错误修复和安全更新进行发布。这意味着**到 2023 年年底，Vue 2 将正式停止维护并到达生命的尽头**。我们相信这将为大多数的生态系统提供了足够长的时间来迁移到 Vue 3。然而，我们也理解可能会有无法在
> Node 中文版文档把 end-of-life 译为了“截止维护日期”我觉得可以借鉴。
> 
> https://nodejs.org/zh-cn/about/releases/
> 
> “Vue 2 在 2023 年底将到达它的截止维护日期”

已按这个修改

2022-08-29 08:35 UTC, Jinjiang approved these changes

2022-08-29 08:37 UTC, Jinjiang commented
![image](https://user-images.githubusercontent.com/206848/187159996-836c2c59-c62a-471b-ba2f-0ea0d0f5d016.png)

补充：有一个已知 bug 这里备忘一下 https://github.com/vuejs/theme/issues/69
主站修复之后会做及时同步

谢谢

2022-08-29 08:38 UTC, merged