Sync #262b5a17
vuejs-translations/docs-zh-cn pull request #625
Opened 2023-01-03 07:04 UTC by wxsms

## Description of Problem

https://github.com/vuejs/docs/compare/49545c20...262b5a17

note: changes of `src/api/composition-api-dependency-injection.md` & `src/api/reactivity-core.md` are already made earlier by Evan.

2023-01-03 08:34 UTC, Justineo requested changes

2023-01-03 08:34 UTC, Justineo commented on src/about/faq.md
> +我们相信这将为大多数的生态系统提供了足够长的时间来迁移到 Vue 3。然而，我们也理解可能会有无法在此时间轴上升级的团队或项目仍需满足其安全及合规需求。我们正在与业内专家合作为有这种需求的团队提供 Vue 2 的扩展支持——如果您的团队预期在 2023 年底之后仍然需要使用 Vue 2，请确保提前计划，详见[Vue 2 拓展 LTS](https://v2.vuejs.org/lts/)。
```suggestion
我们相信这将为大多数的生态系统提供了足够长的时间来迁移到 Vue 3。然而，我们也理解可能会有无法在此时间轴上升级的团队或项目仍需满足其安全及合规需求。我们正在与业内专家合作为有这种需求的团队提供 Vue 2 的扩展支持——如果您的团队预期在 2023 年底之后仍然需要使用 Vue 2，请确保提前计划，详见 [Vue 2 延长 LTS](https://v2.vuejs.org/lts/)。
```

我理解这里应该是延长的意思？

2023-01-03 08:34 UTC, Justineo commented on src/guide/introduction.md
> +- Vue 2 将于 2023 年 12 月 31 日停止维护。详见 [Vue 2 拓展 LTS](https://v2.vuejs.org/lts/)。
```suggestion
- Vue 2 将于 2023 年 12 月 31 日停止维护。详见 [Vue 2 延长 LTS](https://v2.vuejs.org/lts/)。
```

2023-01-04 01:08 UTC, wxsms commented on src/about/faq.md
> +我们相信这将为大多数的生态系统提供了足够长的时间来迁移到 Vue 3。然而，我们也理解可能会有无法在此时间轴上升级的团队或项目仍需满足其安全及合规需求。我们正在与业内专家合作为有这种需求的团队提供 Vue 2 的扩展支持——如果您的团队预期在 2023 年底之后仍然需要使用 Vue 2，请确保提前计划，详见[Vue 2 拓展 LTS](https://v2.vuejs.org/lts/)。
> 我们正在与业内专家合作为有这种需求的团队提供 Vue 2 的_扩展_支持

早前这里是翻译为“拓展”，对应的都是 extended，如果要翻译为“延长”，应该要一起修改？

2023-01-09 08:22 UTC, veaba commented on src/about/faq.md
> +我们相信这将为大多数的生态系统提供了足够长的时间来迁移到 Vue 3。然而，我们也理解可能会有无法在此时间轴上升级的团队或项目仍需满足其安全及合规需求。我们正在与业内专家合作为有这种需求的团队提供 Vue 2 的扩展支持——如果您的团队预期在 2023 年底之后仍然需要使用 Vue 2，请确保提前计划，详见[Vue 2 拓展 LTS](https://v2.vuejs.org/lts/)。
这里的语境看起来是不一样的，原先可以维持。

2023-01-19 15:58 UTC, merged