docs(introduction): proofreading translation
vuejs-translations/docs-zh-cn pull request #7
Opened 2022-01-15 15:40 UTC by KimYangOfCat

校对指引下的文档——introdoction

第一次尝试校对文档，可能不太懂流程和要求，请多多指教和包涵。

最近有时间，希望能有机会深度参与到 Vue 新文档的翻译工作中。

2022-01-16 03:16 UTC, Jinjiang commented
@KimYangOfCat 非常感谢你的参与和贡献！

我简单写了一份流程指南作个参考吧 #8，你的工作很棒，和其他人的工作之间并没有冲突。
另外如果你还在翻译其它页面，个人建议可以分开不同的 PR，这样大家也可以各自独立校对和合并。(比如这个 PR 可以只包含“Review: guide/introduction”，如果继续校对下一个页面，可以单独发另一个 PR“Review: guide/quick-start”)

谢谢

2022-01-16 07:16 UTC, KimYangOfCat commented
@Jinjiang  收到，明白了，新的内容我将新开 PR。谢谢你的流程指南~

2022-01-16 10:27 UTC, wxsms commented on src/guide/introduction.md
> +你可能已经有了些疑问 - 别担心。我们会在接下来的文档中覆盖到每一个细节。现在，请继续读下去，这会让你对 Vue 所提供的功能有一个宏观的认知。
译文54行，原文是在52行，建议在校对时确认一下行号是否一致。我发现上面的两段代码块（25-32、36-46）与目前的原文有所出入。

2022-01-16 12:11 UTC, KimYangOfCat commented on src/guide/introduction.md
> +你可能已经有了些疑问 - 别担心。我们会在接下来的文档中覆盖到每一个细节。现在，请继续读下去，这会让你对 Vue 所提供的功能有一个宏观的认知。
@wxsms Ok ,我检查一下，之前没有注意过这个问题

2022-01-16 12:41 UTC, wxsms commented on src/guide/introduction.md
> +你可能已经有了些疑问 - 别担心。我们会在接下来的文档中覆盖到每一个细节。现在，请继续读下去，这会让你对 Vue 所提供的功能有一个宏观的认知。
与最新的英文版保持一致即可。谢谢。

2022-01-16 12:42 UTC, KimYangOfCat commented
从上面的提议中，我对校对的工作内容有一些疑问，校对除了需要校对翻译内容的准确性，还需要打开英文仓库一一核对内容一致性吗？
@Jinjiang @wxsms 
抱歉，问得更明白一点，方便我展开后续校对工作

2022-01-16 12:49 UTC, wxsms commented
> 从上面的提议中，我对校对的工作内容有一些疑问，校对除了需要校对翻译内容的准确性，还需要打开英文仓库一一核对内容一致性吗？此外，还有什么是值得注意的呢？ @Jinjiang @wxsms 抱歉，问得更明白一点，方便我展开后续校对工作

我理解校对应该是以原文为基准，对译文按照我们约定的翻译规则（术语表/翻译须知等）对不一致或翻译有问题的地方进行修正。如有缺漏、多余部分，均以英文版为准（译者脚注等译文特定内容除外）。谢谢。希望对你有帮助。

2022-01-17 00:25 UTC, KimYangOfCat commented
@wxsms  明白了，已修改

2022-01-19 16:49 UTC, ShenQingchuan commented on src/guide/introduction.md
> +下面是一个最小化的 Vue 计数器示例：
```suggestion
下面是一个小型的 Vue 计数器示例：
```
这里 “最小化” 似乎不是一个一眼看上去符合中文常用语习惯的表达，换成相近意思的词：“简单的”、“小型的” 可能更平实。

2022-01-19 16:54 UTC, Jinjiang commented
发现有 conflict 👀

2022-01-20 03:12 UTC, KimYangOfCat commented
@Jinjiang 已解决

2022-01-20 13:28 UTC, wxsms requested changes

2022-01-20 13:28 UTC, wxsms commented on src/guide/introduction.md
> +下面是一个小型的 Vue 计数器示例：
```suggestion
下面是一个最简的 Vue 计数器示例：
```

2022-01-20 13:28 UTC, wxsms commented on src/guide/introduction.md
>      点击了 {{ count }} 次
根据 [Jinjiang 的建议](https://github.com/vuejs-translations/docs-zh-cn/pull/6#issuecomment-1013804702)，建议对注释以外的代码保留原文

2022-01-20 13:28 UTC, wxsms commented on src/guide/introduction.md
>      点击了 {{ count }} 次
同上

2022-01-20 13:28 UTC, wxsms commented on src/guide/introduction.md
> +你可能已经有了些疑问 - 别担心。我们会在接下来的文档中覆盖到每一个细节。现在，请继续读下去，这会让你对 Vue 所提供的功能有一个宏观的认知。
```suggestion
你可能已经有了些疑问——别担心。我们会在接下来的文档中覆盖到每一个细节。现在，请继续阅读，这会让你对 Vue 所提供的功能有一个宏观的认知。
```

破折号使用中文的。

2022-01-20 13:28 UTC, wxsms commented on src/guide/introduction.md
>  Vue 是一个框架和生态，功能覆盖了大部分前端开发常见的需求。但 Web 世界又是十分多样化的，我们在 Web 上构建的东西可能在形式和规模上有很大不同。考虑到这一点，Vue 被设计成具有灵活性和可逐步集成的特点。根据你的需求场景，Vue 可以按不同的方式使用。
```suggestion
Vue 是一个框架和生态，功能覆盖了大部分前端开发常见的需求。但 Web 世界又是十分多样化的，我们在 Web 上构建的东西可能在形式和规模上有很大不同。考虑到这一点，Vue 被设计成具有灵活性和可逐步集成的特点。根据你的需求场景，Vue 可以按不同的方式使用：
```

2022-01-20 13:28 UTC, wxsms commented on src/guide/introduction.md
>  - 目标为桌面端、移动端、WebGL 甚至是命令行终端
```suggestion
- 目标为桌面端、移动端、WebGL，甚至是命令行终端
```

2022-01-20 13:28 UTC, wxsms commented on src/guide/introduction.md
> +如果你是初学者，可能觉得这些概念令人生畏，别担心！想理解指引和教程文档的内容，只需要具备基础的 HTML 和 JavaScript 知识，而不需要深入理解上面这些方面的知识，你应该能跟上。
```suggestion
如果你是初学者，可能觉得这些概念令人生畏，别担心！想理解指南和教程文档的内容，只需要具备基础的 HTML 和 JavaScript 知识，而无需深入理解它们，你应该能跟上。
```

根据讨论结果，指引是否可以批量替换为指南？

2022-01-20 13:28 UTC, wxsms commented on src/guide/introduction.md
>  如果你是有经验的开发者，对如何以最好的方式在你的项目中引入 Vue，或者是对上述的概念很好奇，我们在 [使用 Vue 的多种方式](/guide/extras/ways-of-using-vue) 中有讨论它们的更多细节。
```suggestion
如果你是有经验的开发者，对于如何以最好的方式在你的项目中引入 Vue，或者是对上述的概念很好奇，我们将在[使用 Vue 的多种方式](/guide/extras/ways-of-using-vue)中讨论有关它们的更多细节。
```

2022-01-20 13:28 UTC, wxsms commented on src/guide/introduction.md
> +无论再怎么灵活，关于 Vue 是如何工作的核心知识在所有这些用例中都是通用的。即使你现在只是一个初学者，随着你不断成长，直到未来有能力实现更雄心勃勃的目标时，这一路上获得的知识将会一直有用。如果你已经是一个老手，你可以根据你要解决的问题来选择使用 Vue 的最佳方式，同时保留相同的生产力。这就是为什么我们称 Vue 为 "渐进式框架"：它是一个可以随着你的需求不断扩展的框架。
```suggestion
无论再怎么灵活，关于 Vue 是如何工作的核心知识在所有这些用例中都是通用的。即使你现在只是一个初学者，随着你的不断成长，直到未来有能力实现更雄心勃勃的目标时，这一路上获得的知识都将会一直有用。如果你已经是一个老手，你可以根据你要解决的问题来选择使用 Vue 的最佳方式，同时保留相同的生产力。这就是为什么我们将 Vue 称之为“渐进式框架”：它是一个可以随着你的需求不断扩展的框架。
```

2022-01-20 13:28 UTC, wxsms commented on src/guide/introduction.md
> +在大多数启用了构建工具的 Vue 项目中，我们可以使用一种类似 HTML 格式的文件来书写 Vue 组件，它被称为 **单文件组件**（即以 `*.vue` 为扩展名的文件，英文缩写为 **SFC**）。顾名思义，Vue 的单文件组件会将一个组件的逻辑（JavaScript），模板（HTML）和样式（CSS）封装在同一个文件里。下面我们将用 单文件组件的格式重写上面的计数器示例：
根据我们在 wiki 达成的共识，括号统一使用半角，谢谢~

2022-01-20 13:28 UTC, wxsms commented on src/guide/introduction.md
> +首先必须要说的是，这两种 API 风格都能够覆盖大部分的应用场景。他们只是同一个系统所提供的两套不同的接口。实际上，选项式 API 也是用组合式 API 实现的！关于 Vue 的基础概念和知识在它们之间都是通用的。
```suggestion
首先，这两种 API 风格都能够覆盖大部分的应用场景。他们只是同一个系统所提供的两套不同的接口。实际上，选项式 API 也是用组合式 API 实现的！关于 Vue 的基础概念和知识在它们之间都是通用的。
```

2022-01-20 13:28 UTC, wxsms commented on src/guide/introduction.md
> +选项式 API 以 “组件实例” 的概念为中心（即上述例子中的 `this`），是基于类的心智模型，如果你有面向对象语言的开发经验可能会更熟悉。它同样抽象出了响应式系统的细节，并强制按照选项来组织代码，这对初学者更友好。
```suggestion
选项式 API 以“组件实例”的概念为中心(即上述例子中的 `this`)，是基于类的心智模型，如果你有面向对象语言的开发经验可能会更熟悉。它同样抽象出了响应式系统的细节，并强制按照选项来组织代码，这对初学者而言更为友好。
```

2022-01-20 13:28 UTC, wxsms commented on src/guide/introduction.md
>  在 [组合式 API FAQ](/guide/extras/composition-api-faq) 章节中，你可以在这两种 API 的风格对比中了解更多组合式 API 所带来的增益。
```suggestion
在[组合式 API FAQ](/guide/extras/composition-api-faq) 章节中，你可以在这两种 API 的风格对比中了解更多组合式 API 所带来的增益。
```

2022-01-20 13:28 UTC, wxsms commented on src/guide/introduction.md
> +你不必在学习阶段就确定自己非要使用哪一种风格。在接下来的文档中我们会为你提供一系列两种风格的代码供你参考，你可以随时通过左上角的 **API 风格偏好** 来做切换。
```suggestion
你不必在学习阶段就确定自己非要使用哪一种风格。在接下来的文档中我们会为你提供一系列两种风格的代码供你参考，你可以随时通过左上角的 **API 风格偏好**来做切换。
```

2022-01-20 13:28 UTC, wxsms commented on src/guide/introduction.md
> +请查看我们的 [FAQ](/about/faq).
```suggestion
请查看我们的 [FAQ](/about/faq)。
```

2022-01-20 13:28 UTC, wxsms commented on src/guide/introduction.md
> +不同的开发者有不同的学习方式。尽管在可能的情况下，我们推荐你通读完所有内容，你可以自由地选择一种你喜欢的学习路径！
```suggestion
不同的开发者有不同的学习方式。你可以自由地选择一种你喜欢的学习路径——尽管我们推荐尽可能地通读所有内容！
```

2022-01-21 04:07 UTC, Justineo requested changes

2022-01-21 04:07 UTC, Justineo commented on src/guide/introduction.md
>  在 [组合式 API FAQ](/guide/extras/composition-api-faq) 章节中，你可以在这两种 API 的风格对比中了解更多组合式 API 所带来的增益。
```suggestion
在[组合式 API FAQ](/guide/extras/composition-api-faq) 章节中，你可以了解更多关于这两种 API 风格的对比以及组合式 API 所带来的潜在收益。
```

2022-01-21 04:07 UTC, Justineo commented on src/guide/introduction.md
> +不同的开发者有不同的学习方式。尽管在可能的情况下，我们推荐你通读完所有内容，你可以自由地选择一种你喜欢的学习路径！
```suggestion
不同的开发者有不同的学习方式。尽管在可能的情况下，我们推荐你通读所有内容，但你还是可以自由地选择一种自己喜欢的学习路径！
```

2022-01-21 04:07 UTC, Justineo commented on src/guide/introduction.md
>    </a>
上面两个链接顺序好像和原文反了

2022-01-21 04:43 UTC, wxsms commented on src/guide/introduction.md
>    </a>
> 上面两个链接顺序好像和原文反了

Evan 貌似最近更新了这一块的文案和顺序，译文没有同步到。

2022-01-21 05:26 UTC, sodatea commented on src/guide/introduction.md
> +单文件组件是 Vue 的特色功能，如果你的用例需要构建的步骤，我们推荐你用它来编写 Vue 组件。你可以在 [为何以及如何使用单文件组件](/guide/scaling-up/sfc) 章节的中学习到更多。但现在，你只需要知道 Vue 会帮你处理所有这些构建配置就好。
`你可以在后续专门的章节里了解更多关于[单文件组件的用法及用途](/guide/scaling-up/sfc)`？

2022-01-21 05:50 UTC, Justineo commented on src/guide/introduction.md
> +单文件组件是 Vue 的特色功能，如果你的用例需要构建的步骤，我们推荐你用它来编写 Vue 组件。你可以在 [为何以及如何使用单文件组件](/guide/scaling-up/sfc) 章节的中学习到更多。但现在，你只需要知道 Vue 会帮你处理所有这些构建配置就好。
感觉不错，比现在的好

2022-01-21 19:34 UTC, KimYangOfCat commented on src/guide/introduction.md
> +下面是一个小型的 Vue 计数器示例：
@Justineo  这样翻译的话，会丢失一部分信息，所以我接受了 @wxsms 的建议

2022-01-21 19:36 UTC, KimYangOfCat commented on src/guide/introduction.md
>      点击了 {{ count }} 次
@wxsms 我认为  Jinjiang 的建议还值再讨论一下，目前就先不修改了。

2022-01-21 19:42 UTC, KimYangOfCat commented on src/guide/introduction.md
>  - 目标为桌面端、移动端、WebGL 甚至是命令行终端
根据上下文的语境，这里是指在列出使用 Vue 的不同方式，我个人理解译为“输出到”似乎也不是很通顺。若一定要意译的话，译为“服务于”会不会好点？
```suggestion
- 服务于桌面端、移动端、WebGL 甚至是命令行终端
```

2022-01-21 19:43 UTC, KimYangOfCat commented on src/guide/introduction.md
> +如果你是初学者，可能觉得这些概念令人生畏，别担心！想理解指引和教程文档的内容，只需要具备基础的 HTML 和 JavaScript 知识，而不需要深入理解上面这些方面的知识，你应该能跟上。
好的，我后续替换为指南

2022-01-21 19:47 UTC, KimYangOfCat commented on src/guide/introduction.md
> +无论再怎么灵活，关于 Vue 是如何工作的核心知识在所有这些用例中都是通用的。即使你现在只是一个初学者，随着你不断成长，直到未来有能力实现更雄心勃勃的目标时，这一路上获得的知识将会一直有用。如果你已经是一个老手，你可以根据你要解决的问题来选择使用 Vue 的最佳方式，同时保留相同的生产力。这就是为什么我们称 Vue 为 "渐进式框架"：它是一个可以随着你的需求不断扩展的框架。
@Justineo 了解，这样处理确实更棒

2022-01-21 19:51 UTC, KimYangOfCat commented on src/guide/introduction.md
> +在大多数启用了构建工具的 Vue 项目中，我们可以使用一种类似 HTML 格式的文件来书写 Vue 组件，它被称为 **单文件组件**（即以 `*.vue` 为扩展名的文件，英文缩写为 **SFC**）。顾名思义，Vue 的单文件组件会将一个组件的逻辑（JavaScript），模板（HTML）和样式（CSS）封装在同一个文件里。下面我们将用 单文件组件的格式重写上面的计数器示例：
> 也被称为 `*.vue`文件
感觉这个翻译有点怪

2022-01-21 20:02 UTC, KimYangOfCat commented on src/guide/introduction.md
>    </a>
那等后续同步吧

2022-01-21 20:46 UTC, KimYangOfCat commented on src/guide/introduction.md
> +在大多数启用了构建工具的 Vue 项目中，我们可以使用一种类似 HTML 格式的文件来书写 Vue 组件，它被称为 **单文件组件**（即以 `*.vue` 为扩展名的文件，英文缩写为 **SFC**）。顾名思义，Vue 的单文件组件会将一个组件的逻辑（JavaScript），模板（HTML）和样式（CSS）封装在同一个文件里。下面我们将用 单文件组件的格式重写上面的计数器示例：
已解决

2022-01-21 20:56 UTC, KimYangOfCat commented on src/guide/introduction.md
> +单文件组件是 Vue 的特色功能，如果你的用例需要构建的步骤，我们推荐你用它来编写 Vue 组件。你可以在 [为何以及如何使用单文件组件](/guide/scaling-up/sfc) 章节的中学习到更多。但现在，你只需要知道 Vue 会帮你处理所有这些构建配置就好。
> `你可以在后续专门的章节里了解更多关于[单文件组件的用法及用途](/guide/scaling-up/sfc)`？

已采纳，感谢

2022-01-21 23:39 UTC, Justineo commented on src/guide/introduction.md
> +在大多数启用了构建工具的 Vue 项目中，我们可以使用一种类似 HTML 格式的文件来书写 Vue 组件，它被称为 **单文件组件**（即以 `*.vue` 为扩展名的文件，英文缩写为 **SFC**）。顾名思义，Vue 的单文件组件会将一个组件的逻辑（JavaScript），模板（HTML）和样式（CSS）封装在同一个文件里。下面我们将用 单文件组件的格式重写上面的计数器示例：
现在这样翻译我认为有语病，扩展名是 vue 而不是 *.vue。

2022-01-24 02:54 UTC, Justineo requested changes

2022-01-24 02:54 UTC, Justineo commented on src/guide/introduction.md
> +下面是一个最简的 Vue 计数器示例：
原文是：

> Here is a minimal example:

对应的就是：

> 下面是一个最基本的示例：

之前原翻译是自己做了扩展的，感觉没有什么必要。

2022-01-24 02:54 UTC, Justineo commented on src/guide/introduction.md
> +无论再怎么灵活，关于 Vue 是如何工作的核心知识在所有这些用例中都是通用的。即使你现在只是一个初学者，随着你的不断成长，直到未来有能力实现更雄心勃勃的目标时，这一路上获得的知识都将会一直有用。如果你已经是一个老手，你可以根据你要解决的问题来选择使用 Vue 的最佳方式，同时保留相同的生产力。这就是为什么我们将 Vue 称之为“渐进式框架”：它是一个可以随着你的需求不断扩展的框架。
```suggestion
无论再怎么灵活，关于 Vue 是如何工作的核心知识在所有这些用例中都是通用的。即使你现在只是一个初学者，随着你的不断成长，直到未来有能力实现更雄心勃勃的目标时，这一路上获得的知识都将会一直有用。如果你已经是一个老手，你可以根据你要解决的问题来选择使用 Vue 的最佳方式，同时保留相同的生产力。这就是为什么我们将 Vue 称为“渐进式框架”：它是一个可以随着你的需求不断扩展的框架。
```

2022-01-24 02:54 UTC, Justineo commented on src/guide/introduction.md
> +在大多数启用了构建工具的 Vue 项目中，我们可以使用一种类似 HTML 格式的文件来书写 Vue 组件，它被称为 **单文件组件**(即以 `*.vue` 为扩展名的文件，英文缩写为 **SFC**)。顾名思义，Vue 的单文件组件会将一个组件的逻辑 (JavaScript)，模板 (HTML) 和样式 (CSS) 封装在同一个文件里。下面我们将用单文件组件的格式重写上面的计数器示例：
> also known as *.vue files

这个地方是在说同一个东西的不同称呼，不是在解释。而且现在的翻译是有语病的，扩展名是 `vue`，不是 `*.vue`。所以这里应该是：

> 也被称为 `*.vue` 文件

2022-01-24 12:52 UTC, KimYangOfCat commented on src/guide/introduction.md
> +下面是一个最简的 Vue 计数器示例：
好吧

2022-01-24 12:55 UTC, KimYangOfCat commented on src/guide/introduction.md
> +在大多数启用了构建工具的 Vue 项目中，我们可以使用一种类似 HTML 格式的文件来书写 Vue 组件，它被称为 **单文件组件**(即以 `*.vue` 为扩展名的文件，英文缩写为 **SFC**)。顾名思义，Vue 的单文件组件会将一个组件的逻辑 (JavaScript)，模板 (HTML) 和样式 (CSS) 封装在同一个文件里。下面我们将用单文件组件的格式重写上面的计数器示例：
已合并

2022-01-24 16:19 UTC, merged