Sync #5b045c22
vuejs-translations/docs-zh-cn pull request #709
Opened 2023-05-14 03:19 UTC by ikxin

## Description of Problem

[vuejs/docs@3cb76a49...5b045c22](https://github.com/vuejs/docs/compare/3cb76a49...5b045c22)

2023-05-14 06:00 UTC, KiritaniAyaka commented on src/guide/typescript/overview.md
> +- Render function / JSX components: [`defineComponent()`'s function signature](/api/general.html#function-signature)
```suggestion
### 使用 TSX

Vue 也支持使用 JSX / TSX 编写组件。详情请查阅[渲染函数 & JSX](/guide/extras/render-function.html#jsx-tsx)。

## 泛型组件 {#generic-components}

泛型组件支持两种使用方式：

- 在单文件组件中：[在 `<script setup>` 上使用 `generic` 属性](/api/sfc-script-setup.html#generics)
- 渲染函数 / JSX 组件：[`defineComponent()` 的函数签名](/api/general.html#function-signature)
```

2023-05-14 08:59 UTC, KiritaniAyaka requested changes
根据约定修正了一些错误并翻译了一些未翻译的部分

2023-05-14 08:59 UTC, KiritaniAyaka commented on src/api/sfc-script-setup.md
> +- In version 3.2 and below, the generic type parameter for `defineProps()` were limited to a type literal or a reference to a local interface.
```suggestion
- 在 3.2 及以下版本中，`defineProps()`  的泛型类型参数只能使用类型字面量或者本地接口的引用。
```

2023-05-14 08:59 UTC, KiritaniAyaka commented on src/api/sfc-script-setup.md
> +  This limitation has been resolved in 3.3. The latest version of Vue supports referencing imported and a limited set of complex types in the type parameter position. However, because the type to run
```suggestion
  这个限制已经在 3.3 版本中解决。最新版本的 Vue 支持在类型参数的位置引用导入的和有限的复杂类型。然而，由于类型到运行时的转换仍然基于 AST，因此并不支持使用需要实际类型分析的复杂类型，例如条件类型等。你可以在单个 prop 的类型上使用条件类型，但不能对整个 props 对象使用。
```

2023-05-14 08:59 UTC, KiritaniAyaka commented on src/api/reactivity-utilities.md
> +- **Type**
```suggestion
## toValue() <sup class="vt-badge" data-text="3.3+" /> {#tovalue}

将 values / refs / getters 规范化为值。这与 [unref()](#unref) 类似，不同的是此函数也会规范化 getter 函数。如果参数是一个 getter，它将会被调用并且返回它的返回值。

这可以在[组合式函数](/guide/reusability/composables.html)中使用，用来规范化一个可以是值、ref、或者 getter 的参数。

- **类型**
```

2023-05-14 08:59 UTC, KiritaniAyaka commented on src/api/reactivity-utilities.md
> +- **Example**
```suggestion
- **示例**
```

2023-05-14 08:59 UTC, KiritaniAyaka commented on src/api/reactivity-utilities.md
> +  Normalizing arguments in composables:
```suggestion
  在组合式函数中规范化参数：
```

2023-05-14 08:59 UTC, KiritaniAyaka commented on src/api/reactivity-utilities.md
> +  // this composable supports any of the following:
```suggestion
  // 这个组合式函数支持以下的任意形式：
```

2023-05-14 08:59 UTC, KiritaniAyaka commented on src/api/reactivity-utilities.md
> +      // react to id changes
```suggestion
      // 处理 id 变更
```

2023-05-14 08:59 UTC, KiritaniAyaka commented on src/api/utility-types.md
> +- **Example**
```suggestion
## MaybeRef\<T> {#mayberef}

`T | Ref<T>` 的别名。对于标注[组合式函数](/guide/reusability/composables.html)的参数很有用。

- 仅在 3.3+ 版本中支持。

## MaybeRefOrGetter\<T> {#maybereforgetter}

`T | Ref<T> | (() => T)` 的别名。对于标注[组合式函数](/guide/reusability/composables.html)的参数很有用。

- 仅在 3.3+ 版本中支持。

## ExtractPropTypes\<T> {#extractproptypes}

从运行时的 props 选项对象中提取 props 类型。提取到的类型是面向内部的，也就是说组件接收到的是解析后的 props。这意味着 boolean 类型的 props 和带有默认值的 props 总是一个定义的值，即使它们不是必需的。

要提取面向外部的 props，即父组件允许传递的 props，请使用 [`ExtractPublicPropTypes`](#extractpublicproptypes)。

- **示例**
```

2023-05-14 08:59 UTC, KiritaniAyaka commented on src/api/utility-types.md
> +- **Example**
```suggestion
从运行时的 props 选项对象中提取 prop。提取的类型是面向外部的，即父组件允许传递的 props。

- **示例**
```

2023-05-14 08:59 UTC, KiritaniAyaka commented on src/guide/scaling-up/testing.md
> +- [Vitest](https://vitest.dev/) for components or composables that render headlessly (e.g. the [`useFavicon`](https://vueuse.org/core/useFavicon/#usefavicon) function in VueUse). Components and DOM c
```suggestion
- [Vitest](https://vitest.dev/) 对于组件和组合式函数都采用无头渲染的方式 (例如 VueUse 中的 [`useFavicon`](https://vueuse.org/core/useFavicon/#usefavicon) 函数)。组件和 DOM 都可以通过 [@vue/test-utils](https://github.com/vuejs/test-utils) 来测试。
```

[vuejs/docs/commit/acac67f](https://github.com/vuejs/docs/commit/acac67f5fdde6cad7982bbb376faf6a4940be580)

2023-05-14 08:59 UTC, KiritaniAyaka commented on src/guide/scaling-up/testing.md
> +The main differences between Vitest and browser-based runners are speed and execution context. In short, browser-based runners, like Cypress, can catch issues that node-based runners, like Vitest, ca
```suggestion
Vitest 和基于浏览器的运行器之间的主要区别是速度和执行上下文。简而言之，基于浏览器的运行器，如 Cypress，可以捕捉到基于 Node 的运行器（如 Vitest）所不能捕捉的问题（比如样式问题、原生 DOM 事件、Cookies、本地存储和网络故障），但基于浏览器的运行器比 Vitest *慢几个数量级*，因为它们要执行打开浏览器，编译样式表以及其他步骤。Cypress 是一个基于浏览器的运行器，支持组件测试。请阅读 [Vitest 文档的“比较”这一章](https://vitest.dev/guide/comparisons.html#cypress) 了解 Vitest 和 Cypress 最新的比较信息。
```

[vuejs/docs/commit/acac67f](https://github.com/vuejs/docs/commit/acac67f5fdde6cad7982bbb376faf6a4940be580)

2023-05-14 08:59 UTC, KiritaniAyaka commented on src/guide/scaling-up/testing.md
> +We recommend using `@vue/test-utils` for testing components in applications. `@testing-library/vue` has issues with testing asynchronous component with Suspense, so it should be used with caution.
```suggestion
我们推荐在应用中使用 `@vue/test-utils` 测试组件。`@testing-library/vue` 在测试带有 Suspense 的异步组件时存在问题，在使用时需要谨慎。
```

2023-05-14 08:59 UTC, KiritaniAyaka commented on src/guide/scaling-up/testing.md
> +- [`@vue/test-utils`](https://github.com/vuejs/test-utils) is the official low-level component testing library that was written to provide users access to Vue specific APIs. It's also the lower-level
```suggestion
- [`@vue/test-utils`](https://github.com/vuejs/test-utils) 是官方的底层组件测试库，用来提供给用户访问 Vue 特有的 API。`@testing-library/vue` 也是基于此库构建的。
```

2023-05-14 08:59 UTC, KiritaniAyaka commented on src/guide/scaling-up/testing.md
> +- [`@testing-library/vue`](https://github.com/testing-library/vue-testing-library) is a Vue testing library focused on testing components without relying on implementation details. Its guiding princi
```suggestion
- [`@testing-library/vue`](https://github.com/testing-library/vue-testing-library) 是一个专注于测试组件而不依赖于实现细节的 Vue 测试库。它的指导原则是：测试越是类似于软件的使用方式，它们就能提供越多的信心。
```

2023-05-14 11:07 UTC, wxsms commented on src/api/general.md
> +  // function syntax (requires 3.3+)
```suggestion
  // 函数语法 (需要 3.3+)
```

2023-05-14 11:07 UTC, wxsms commented on src/api/general.md
> +  // options syntax
```suggestion
  // 选项语法
```

2023-05-14 11:07 UTC, wxsms commented on src/api/general.md
> +  `defineComponent()` 还有一种备用签名，旨在与 Composition API 和 [render 函数或 JSX](/guide/extras/render-function.html) 一起使用。
```suggestion
  `defineComponent()` 还有一种备用签名，旨在与组合式 API 和 [渲染函数或 JSX](/guide/extras/render-function.html) 一起使用。
```

2023-05-14 11:07 UTC, wxsms commented on src/api/general.md
> +      // use Composition API here like in <script setup>
```suggestion
      // 就像在 <script setup> 中一样使用组合式 API
```

2023-05-14 11:07 UTC, wxsms commented on src/api/general.md
> +  此签名的主要用例是使用 TypeScript（特别是使用 TSX ），因为它支持泛型：
```suggestion
  此签名的主要用例是使用 TypeScript (特别是使用 TSX )，因为它支持泛型：
```

2023-05-14 11:07 UTC, wxsms commented on src/api/general.md
> +      // use Composition API here like in <script setup>
```suggestion
      // 就像在 <script setup> 中一样使用组合式 API
```

2023-05-14 11:07 UTC, wxsms commented on src/api/options-rendering.md
> +提供一个选项，在渲染函数中以编程方式使用插槽时辅助类型推断。仅在 Vue 3.3+ 中支持。
```suggestion
一个在渲染函数中以编程方式使用插槽时辅助类型推断的选项。仅在 Vue 3.3+ 中支持。
```

2023-05-15 01:47 UTC, wxsms commented on src/api/general.md
> +  与其传递选项对象不同，需要传入一个函数。这个函数的工作方式与 Composition API [`setup()`](/api/composition-api-setup.html#composition-api-setup) 函数相同：它接收 props 和 setup 上下文。返回值应该是一个渲染函数——支持 `h()` 和 JSX：
```suggestion
  与传递选项对象不同的是，它需要传入一个函数。这个函数的工作方式与组合式 API 的 [`setup()`](/api/composition-api-setup.html#composition-api-setup) 函数相同：它接收 props 和 setup 上下文。返回值应该是一个渲染函数——支持 `h()` 和 JSX：
```

2023-05-15 01:47 UTC, wxsms commented on src/api/general.md
> +  在将来，我们计划提供一个 Babel 插件，自动推断并注入运行时 props（就像在 SFC 中的 `defineProps` 一样），以便可以省略运行时 props 的声明。
```suggestion
  在将来，我们计划提供一个 Babel 插件，自动推断并注入运行时 props (就像在 SFC 中的 `defineProps` 一样)，以便省略运行时 props 的声明。
```

2023-05-15 01:47 UTC, wxsms commented on src/api/options-rendering.md
> +  该选项的运行时值不会被使用。实际类型应使用 `SlotsType` 类型辅助工具进行类型转换来声明：
```suggestion
  该选项的运行时值不会被使用。实际类型应通过 `SlotsType` 类型辅助工具进行类型转换来声明：
```

2023-05-15 01:47 UTC, wxsms commented on src/api/reactivity-utilities.md
>  基于响应式对象上的一个属性，创建一个对应的 ref。这样创建的 ref 与其源属性保持同步：改变源属性的值将更新 ref 的值，反之亦然。
本行需删除

2023-05-15 01:47 UTC, wxsms commented on src/api/reactivity-utilities.md
> +Can also be used to create a ref for a property on a source reactive object. The created ref is synced with its source property: mutating the source property will update the ref, and vice-versa.
```suggestion
也可以基于响应式对象上的一个属性，创建一个对应的 ref。这样创建的 ref 与其源属性保持同步：改变源属性的值将更新 ref 的值，反之亦然。
```

2023-05-15 01:47 UTC, wxsms commented on src/api/reactivity-utilities.md
> +Can be used to normalize values / refs / getters into refs (3.3+).
```suggestion
可以将值、refs 或 getters 规范化为 refs (3.3+)。
```

2023-05-15 01:47 UTC, wxsms commented on src/api/reactivity-utilities.md
>    即使源属性当前不存在，`toRef()` 也会返回一个可用的 ref。这让它在处理可选 props 的时候格外实用，相比之下 [`toRefs`](#torefs) 就不会为可选 props 创建对应的 refs。
```suggestion
  当使用对象属性签名时，即使源属性当前不存在，`toRef()` 也会返回一个可用的 ref。这让它在处理可选 props 的时候格外实用，相比之下 [`toRefs`](#torefs) 就不会为可选 props 创建对应的 refs。
```

2023-05-15 01:47 UTC, wxsms commented on src/api/reactivity-utilities.md
> +将 values / refs / getters 规范化为值。这与 [unref()](#unref) 类似，不同的是此函数也会规范化 getter 函数。如果参数是一个 getter，它将会被调用并且返回它的返回值。
```suggestion
将值、refs 或 getters 规范化为值。这与 [unref()](#unref) 类似，不同的是此函数也会规范化 getter 函数。如果参数是一个 getter，它将会被调用并且返回它的返回值。
```

2023-05-15 01:47 UTC, wxsms commented on src/api/reactivity-utilities.md
> +这可以在[组合式函数](/guide/reusability/composables.html)中使用，用来规范化一个可以是值、ref、或者 getter 的参数。
```suggestion
这可以在[组合式函数](/guide/reusability/composables.html)中使用，用来规范化一个可以是值、ref 或 getter 的参数。
```

2023-05-15 02:14 UTC, wxsms commented on src/api/sfc-script-setup.md
>  ## 针对 TypeScript 的功能 {#typescript-only-features}
此处同步有误，请检查源文件 351 行，谢谢。

2023-05-15 02:14 UTC, wxsms commented on src/api/utility-types.md
>  :::tip
遗漏了 L202-203 的内容。

2023-05-15 02:14 UTC, wxsms commented on src/guide/essentials/forms.md
> +`v-model` 会忽略任何表单元素上初始的 `value`、`checked` 或 `selected` attribute。它将始终将当前绑定的 JavaScript 状态视为数据的正确来源。你应该在 JavaScript 中使用<span class="options-api"> `data` 选项</span><span class="composition-api">[响应式系统的
```suggestion
`v-model` 会忽略任何表单元素上初始的 `value`、`checked` 或 `selected` attribute。它将始终将当前绑定的 JavaScript 状态视为数据的正确来源。你应该在 JavaScript 中使用<span class="options-api"> [`data`](/api/options-state.html#data) 选项</span><span class="composition-api">[响应式系统的 API](/api/reactivity-core.html#reactivity-api-core) </span>来声明该初始值。
```

2023-05-15 04:26 UTC, ikxin commented on src/api/utility-types.md
>  :::tip
我看到这个已经存在

https://github.com/vuejs/docs/blob/main/src/api/utility-types.md?plain=1#L202

2023-05-15 06:01 UTC, wxsms commented on src/api/sfc-script-setup.md
> +## Generics <sup class="vt-badge ts" /> {#generics}
```suggestion
## 泛型 <sup class="vt-badge ts" /> {#generics}
```

2023-05-15 06:03 UTC, wxsms commented on src/api/reactivity-utilities.md
>  基于响应式对象上的一个属性，创建一个对应的 ref。这样创建的 ref 与其源属性保持同步：改变源属性的值将更新 ref 的值，反之亦然。
```suggestion
也可以基于响应式对象上的一个属性，创建一个对应的 ref。这样创建的 ref 与其源属性保持同步：改变源属性的值将更新 ref 的值，反之亦然。
```

2023-05-15 06:08 UTC, merged