Sync #ff263e7d
vuejs-translations/docs-zh-cn pull request #723
Opened 2023-06-15 03:05 UTC by wxsms

## Description of Problem

https://github.com/vuejs/docs/compare/f618a3a5...ff263e7d

2023-06-19 04:07 UTC, Justineo requested changes

2023-06-19 04:07 UTC, Justineo commented on src/guide/components/provide-inject.md
> +The third parameter indicates the default value should be treated as a factory function.
标记下 TODO？下同

2023-06-19 04:07 UTC, Justineo commented on src/guide/extras/composition-api-faq.md
> +### 我可以在同个组件中使用两种 API 吗？ {#can-i-use-both-apis-in-the-same-component}
```suggestion
### 可以在同一个组件中使用两种 API 吗？ {#can-i-use-both-apis-in-the-same-component}
```

2023-06-19 04:07 UTC, Justineo commented on src/guide/quick-start.md
> +导入映射表是一个相对较新的浏览器功能。请确保使用其[支持范围](https://caniuse.com/import-maps)内的浏览器。特别注意的是，它只在 Safari 16.4 以上版本中被支持。
```suggestion
导入映射表是一个相对较新的浏览器功能。请确保使用其[支持范围](https://caniuse.com/import-maps)内的浏览器。请注意，只有 Safari 16.4 以上版本支持。
```

2023-06-19 13:42 UTC, wxsms commented on src/api/application.md
> +- **参考**[指南 - 创建一个 Vue 应用实例](/guide/essentials/application)
因为看到英文版删除了这个冒号，所以做了同步。

2023-06-19 13:53 UTC, wxsms commented on src/guide/components/provide-inject.md
> +The third parameter indicates the default value should be treated as a factory function.
漏了这部分，已翻译

2023-06-25 11:32 UTC, Justineo requested changes

2023-06-25 11:32 UTC, Justineo commented on src/guide/components/v-model.md
> +这里是另一个使用多个 `v-model` 且带有不同参数的修饰符的例子：
```suggestion
这里是另一个例子，展示了在使用多个不同参数的 `v-model` 时使用修饰符：
```

2023-06-25 11:55 UTC, wxsms commented on src/guide/components/v-model.md
> +这里是另一个使用多个 `v-model` 且带有不同参数的修饰符的例子：
```suggestion
这里是另一个例子，展示了如何在使用多个不同参数的 `v-model` 时使用修饰符：
```

2023-06-25 12:30 UTC, Justineo commented on src/guide/components/v-model.md
> +这里是另一个使用多个 `v-model` 且带有不同参数的修饰符的例子：
👌

2023-06-25 16:04 UTC, Justineo approved these changes

2023-06-25 16:22 UTC, Justineo requested changes

2023-06-25 16:22 UTC, Justineo commented on src/api/composition-api-lifecycle.md
> +- **参考**[Reactivity in Depth](/guide/extras/reactivity-in-depth)
```suggestion
- **参考**[深入响应式系统](/guide/extras/reactivity-in-depth)
```

2023-06-25 16:22 UTC, Justineo commented on src/api/composition-api-lifecycle.md
> +- **参考**[Reactivity in Depth](/guide/extras/reactivity-in-depth)
```suggestion
- **参考**[深入响应式系统](/guide/extras/reactivity-in-depth)
```

2023-06-25 16:22 UTC, Justineo commented on src/api/application.md
> +- **参考**[Vue 与 Web Components](/guide/extras/web-components)
```suggestion
- **参考** [Vue 与 Web Components](/guide/extras/web-components)
```

2023-06-25 16:22 UTC, Justineo commented on src/api/built-in-components.md
> +- **参考**[`<Transition>` 指南](/guide/built-ins/transition)
```suggestion
- **参考** [`<Transition>` 指南](/guide/built-ins/transition)
```

2023-06-25 16:22 UTC, Justineo commented on src/api/composition-api-lifecycle.md
> +- **参考**[Guide - 缓存实例的生命周期](/guide/built-ins/keep-alive#lifecycle-of-cached-instance)
```suggestion
- **参考**[指南 - 缓存实例的生命周期](/guide/built-ins/keep-alive#lifecycle-of-cached-instance)
```

2023-06-25 16:22 UTC, Justineo commented on src/api/options-composition.md
> +
TODO

2023-06-25 16:22 UTC, Justineo commented on src/api/options-state.md
> +- **参考** [事件处理](/guide/essentials/event-handling)
```suggestion
- **参考**[事件处理](/guide/essentials/event-handling)
```

2023-06-25 16:22 UTC, Justineo commented on src/guide/essentials/reactivity-fundamentals.md
> +### Why Refs? \*\* {#why-refs}
TODO

2023-06-25 16:22 UTC, Justineo commented on src/guide/quick-start.md
> +:::tip 导入映射表的浏览器支持情况
```suggestion
:::tip
导入映射表的浏览器支持情况
```

2023-06-25 16:22 UTC, Justineo commented on src/guide/scaling-up/tooling.md
>  - [Chrome 插件商店页](https://chrome.google.com/webstore/detail/vuejs-devtools/nhdogjmejiglipccpnnnanhbledajbpd)
```suggestion
- [Chrome 扩展商店页](https://chrome.google.com/webstore/detail/vuejs-devtools/nhdogjmejiglipccpnnnanhbledajbpd)
```

2023-06-25 16:22 UTC, Justineo commented on src/guide/scaling-up/tooling.md
> +- [Edge 拓展](https://microsoftedge.microsoft.com/addons/detail/vuejs-devtools/olofadcdnkkjdfgjcmjaadnlehnnihnl)
```suggestion
- [Edge 扩展](https://microsoftedge.microsoft.com/addons/detail/vuejs-devtools/olofadcdnkkjdfgjcmjaadnlehnnihnl)
```

2023-06-26 01:45 UTC, Justineo commented on src/api/built-in-special-attributes.md
> +- **参考**[指南- 列表渲染 - 通过 `key` 管理状态](/guide/essentials/list#maintaining-state-with-key)
```suggestion
- **参考**[指南 - 列表渲染 - 通过 `key` 管理状态](/guide/essentials/list#maintaining-state-with-key)
```

2023-06-26 01:48 UTC, wxsms commented on src/guide/quick-start.md
> +:::tip 导入映射表的浏览器支持情况
这个原文是在同一行的哦

2023-06-26 01:50 UTC, Justineo commented on src/guide/quick-start.md
> +:::tip 导入映射表的浏览器支持情况
好的，我看错了，忽略吧

2023-06-30 10:34 UTC, veaba commented
@wxsms 前面有个 deps bot 合并到 main 分支了，这里需要处理下冲突。

2023-07-18 03:19 UTC, merged