翻译Code Of Conduct页面
vuejs-translations/docs-zh-cn pull request #727
Opened 2023-06-21 07:01 UTC by GuoJikun

### 在创建 pull request 之前

请确认：

- [x ] 我已经阅读过项目的 [wiki](https://github.com/vuejs-translations/docs-zh-cn/wiki) 了解相关注意事项。
- [x ] 我对翻译内容的改动不包含基于英文原版的扩展、删减或演绎 (如有，请移步至[英文文档仓库](https://github.com/vuejs/docs)讨论，相关结论会被定期从英文版同步)

### 问题描述
翻译[Code Of Conduct](https://vuejs.org/about/coc.html) 页面

2023-06-21 08:40 UTC, Justineo requested changes

2023-06-21 08:40 UTC, Justineo commented on src/about/coc.md
> +项目维护者有权利和责任删除、编辑或拒绝不符合本行为准则的评论、提交、代码、wiki编辑、问题和其他贡献，或暂时或永久禁止任何贡献者的其他行为，他们认为不适当、威胁、冒犯或有害。
```suggestion
项目维护者有权利和责任删除、编辑或拒绝不符合本行为准则的评论、提交、代码、wiki 编辑、问题和其他贡献，或暂时/永久禁止任何贡献者的其他他们认为不适当、威胁、冒犯或有害的行为。
```

2023-06-21 08:40 UTC, Justineo commented on src/about/coc.md
> +当个人代表项目或其社区时，本行为准则适用于项目空间和公共空间。代表项目或社区的例子包括使用官方项目的电子邮件地址，通过官方社交媒体帐户发布信息，或在在线或离线活动中担任指定代表。项目维护人员可以进一步定义和澄清项目的表示形式。
```suggestion
当个人代表项目或其社区时，本行为准则同时适用于项目空间和公共空间。代表项目或社区的例子包括使用项目官方的电子邮件地址、通过官方社交媒体帐户发布信息、或在线上或线下活动中担任指定代表。代表项目的含义也可以由项目维护人员进一步定义和明确。
```

最后一句稍微意译了一下。

2023-06-21 08:40 UTC, Justineo commented on src/about/coc.md
> +辱骂、骚扰或其他不可接受的行为可以通过community@vuejs.org联系项目团队来报告。所有的投诉都将被审查和调查，并根据具体情况作出必要和适当的回应。项目组有义务对事件的报道者保密。具体执行政策的进一步详情可另行公布。
```suggestion
辱骂、骚扰或其他不可接受的行为可以通过 community@vuejs.org 联系项目团队来举报。所有的投诉都将被审查和调查，并根据具体情况作出必要和适当的回应。项目组有义务对事件的举报者保密。具体执行政策的进一步详情可另行公布。
```

2023-06-21 08:40 UTC, Justineo commented on src/about/coc.md
> +项目维护者如果不忠实遵守或执行行为准则，可能会面临由项目领导的其他成员所决定的暂时或永久的后果。
```suggestion
项目维护者如果不遵守或善意地执行行为准则，可能会面临由其他的项目领导成员所决定的暂时或永久的不利后果。
```

2023-06-21 08:40 UTC, Justineo commented on src/about/coc.md
> +该行为准则改编自《[Contributor Covenant](https://www.contributor-covenant.org/)》 [1.4版本](https://www.contributor-covenant.org/version/1/4/code-of-conduct.html)。
```suggestion
该行为准则改编自《[Contributor Covenant](https://www.contributor-covenant.org/)》 [1.4 版本](https://www.contributor-covenant.org/version/1/4/code-of-conduct.html)。
```

2023-06-21 09:30 UTC, GuoJikun commented on src/about/coc.md
> +## 范围 { #scope }
这个没必要修改，其他页面的翻译就是这样书写的。
另外咨询下，我只点击![image](https://github.com/vuejs-translations/docs-zh-cn/assets/21582741/d01e972e-1c0a-4b19-bb7b-bc09af5cb271)就可以了吧

2023-06-22 01:59 UTC, Justineo commented on src/about/coc.md
> +## 范围 { #scope }
这里括号里不需要空格吧

2023-06-22 10:47 UTC, GuoJikun commented on src/about/coc.md
> +## 范围 { #scope }
不好意思，我看错了

2023-06-25 11:23 UTC, Justineo approved these changes

2023-06-25 11:25 UTC, Justineo commented
感谢 @GuoJikun 新增了 CoC 的翻译，这部分请大家也看下 /cc @vuejs-translations/zh-cn

2023-06-25 11:26 UTC, Justineo commented on src/about/coc.md
> +## 范围 { #scope }
PS 应该是点 Commit suggestion，我帮你重新提交了

2023-06-26 01:30 UTC, watonyweng approved these changes
LGMT

2023-06-26 03:01 UTC, merged