feat: translate todo in reactivity-fundamentals.md
vuejs-translations/docs-zh-cn pull request #746
Opened 2023-07-18 09:12 UTC by wxsms

### 在创建 pull request 之前

请确认：

- [x] 我已经阅读过项目的 [wiki](https://github.com/vuejs-translations/docs-zh-cn/wiki) 了解相关注意事项。
- [x] 我对翻译内容的改动不包含基于英文原版的扩展、删减或演绎 (如有，请移步至[英文文档仓库](https://github.com/vuejs/docs)讨论，相关结论会被定期从英文版同步)

### 问题描述

2023-07-21 02:49 UTC, sfilata approved these changes

2023-07-22 07:02 UTC, KiritaniAyaka requested changes

2023-07-23 08:08 UTC, Jinjiang commented on src/guide/essentials/reactivity-fundamentals.md
> +3. **不利于解构**：当我们将响应式对象的属性解构为本地变量时，或者将该属性传递给函数时，我们将丢失响应性连接：
```suggestion
3. **对解构操作不友好**：当我们将响应式对象的属性解构为本地变量时，或者将该属性传递给函数时，我们将丢失响应性连接：
```

2023-07-23 08:08 UTC, Jinjiang commented on src/guide/essentials/reactivity-fundamentals.md
> +模板中的 ref 解包仅适用于 ref 是模板渲染上下文中的顶级属性的情况。
```suggestion
在模板渲染上下文中，只有顶级的 ref 属性才会被解包。
```

做了一定的简化

2023-07-23 08:08 UTC, Jinjiang commented on src/guide/essentials/reactivity-fundamentals.md
> +另一个需要注意的点是，如果 ref 是文本插值的最终计算值(即 <code v-pre>{{ }}</code> 标签)，那么它将被解包，因此以下内容将渲染为 `1`：
```suggestion
另一个需要注意的点是，如果 ref 是文本插值的最终计算值 (即 <code v-pre>{{ }}</code> 标签)，那么它将被解包，因此以下内容将渲染为 `1`：
```

2023-07-23 15:29 UTC, Jinjiang approved these changes

2023-07-23 15:29 UTC, merged