translate glossary
vuejs-translations/docs-zh-cn pull request #748
Opened 2023-07-19 02:43 UTC by wxsms

### 在创建 pull request 之前

请确认：

- [x] 我已经阅读过项目的 [wiki](https://github.com/vuejs-translations/docs-zh-cn/wiki) 了解相关注意事项。
- [x] 我对翻译内容的改动不包含基于英文原版的扩展、删减或演绎 (如有，请移步至[英文文档仓库](https://github.com/vuejs/docs)讨论，相关结论会被定期从英文版同步)

### 问题描述

close #747

2023-08-10 02:36 UTC, Jinjiang reviewed
暂时 review 到了前 100 行

2023-08-10 02:36 UTC, Jinjiang commented on src/glossary/index.md
> +Vue 的[单文件组件](#single-file-component)编译器支持各种宏，例如 `defineProps()`、`defineEmits()` 和 `defineExpose()`。这些宏有意设计成类似正常的 JavaScript 函数，以便它们可以利用 JavaScript / TypeScript 中的相同解析器和类型推断工具。然而，它们不是在浏览器中运行的实际函数。这些是编
```suggestion
Vue 的[单文件组件](#single-file-component)编译器支持各种宏，例如 `defineProps()`、`defineEmits()` 和 `defineExpose()`。这些宏有意设计得像是普通的 JavaScript 函数，以便它们可以利用 JavaScript / TypeScript 中的相同解析器和类型推断工具。然而，它们不是在浏览器中运行的实际函数。这些特殊字符串会被编译器检测到并替换为实际真正运行的 JavaScript 代码。
```

2023-08-10 02:36 UTC, Jinjiang commented on src/glossary/index.md
> +宏在使用上有一些不适用于正常 JavaScript 代码的限制。例如，你可能认为 `const dp = defineProps` 可以让你为 `defineProps` 创建一个别名，但实际上它会导致错误。对 `defineProps()` 可传入的值也有限制，因为“参数”必须由编译器而不是在运行时处理。
```suggestion
宏在使用上有一些不适用于普通 JavaScript 代码的限制。例如，你可能认为 `const dp = defineProps` 会为 `defineProps` 创建一个别名，但实际上它会导致错误。相同的限制也存在于传入 `defineProps()` 的值，因为“参数”必须由编译器处理，而不是在运行时。
```

2023-08-10 02:36 UTC, Jinjiang commented on src/glossary/index.md
> +组件是 Vue 提供的用于将 UI 拆分为较小的部分的主要机制，既可以提高可维护性，也允许代码重用。
```suggestion
组件是 Vue 提供的将 UI 拆成较小部分的主要机制，既可以提高可维护性，也允许代码重用。
```

2023-08-10 02:36 UTC, Jinjiang commented on src/glossary/index.md
> +一个 Vue 组件是一个对象。所有属性都是可选的，但是模板或渲染函数是组件渲染所必需的。例如，以下对象将是一个有效的组件：
```suggestion
一个 Vue 组件是一个对象。所有属性都是可选的，但是必须有用于组件渲染的模板或渲染函数二选一。例如，以下对象将是一个有效的组件：
```

2023-08-10 02:36 UTC, Jinjiang commented on src/glossary/index.md
> +在实践中，大多数 Vue 应用都是通过[单文件组件](#single-file-component) (`.vue` 文件) 编写的。虽然这些组件乍一看可能不像是对象，但单文件组件编译器会将它们转换为一个对象，它将用作文件的默认导出。从外部的角度来看，`.vue` 文件只是一个导出组件对象的 ES 模块。
```suggestion
在实践中，大多数 Vue 应用都是通过[单文件组件](#single-file-component) (`.vue` 文件) 编写的。虽然这些组件乍一看不是对象，但单文件组件编译器会将它们转换为用作文件默认导出的一个对象。从外部来看，`.vue` 文件只是导出一个组件对象的 ES 模块。
```

2023-08-10 02:36 UTC, Jinjiang commented on src/glossary/index.md
> +*自定义元素*是现代 Web 浏览器中实现的 [Web Components](#web-component) 标准的一个特性。它指的是在 HTML 标记中使用自定义 HTML 元素的能力，以在页面的该位置导入一个 Web Component。
```suggestion
*自定义元素*是现代 Web 浏览器中实现的 [Web Components](#web-component) 标准的一个特性。它指的是在 HTML 标记中使用自定义 HTML 元素，以在页面的该位置加入一个 Web Component 的能力。
```

2023-08-10 02:36 UTC, Jinjiang commented on src/glossary/index.md
> +自定义元素不应该与在另一个 Vue 组件的模板中包含 Vue 组件的能力混淆。自定义元素是用于创建 Web Components 的，而不是 Vue 组件。
```suggestion
自定义元素不应该与在 Vue 组件的模板中包含另一个 Vue 组件的能力混淆。自定义元素是用于创建 Web Components 的，而不是 Vue 组件。
```

2023-08-10 16:32 UTC, Jinjiang commented on src/glossary/index.md
> +片段也被模板编译器用作包装多个动态节点的方式，例如通过 `v-for` 或 `v-if` 创建的节点。这允许向 [VDOM](#virtual-dom) 补丁算法传递额外的提示。这些大部分都是在内部处理的，但你可能直接遇到的一个例子是在 `<template>` 标签上使用 `v-for` 的 `key`。在这种情况下，`key` 会作为[参数](#prop)添加到片段的 VNode。
```suggestion
片段也作为包装多个动态节点的一种方式被用于模板编译器，例如通过 `v-for` 或 `v-if` 创建的节点。这允许我们向 [VDOM](#virtual-dom) 补丁算法传递额外的提示。这些大部分都是在内部处理的，但你可能会直接遇到的一种情况是在 `<template>` 标签上使用 `v-for` 的 `key`。在此，`key` 会作为 [prop](#prop) 添加到片段的 VNode。
```

2023-08-10 16:36 UTC, Jinjiang commented on src/glossary/index.md
> +片段节点当前被渲染为 DOM 上的空文本节点，尽管这是一个实现细节。但如果你使用 `$el` 或尝试使用内置的浏览器 API 遍历 DOM 时，可能会遇到这些文本节点。
```suggestion
片段节点当前在 DOM 上被渲染为了空文本节点，但这只是一个实现细节。当你使用 `$el` 或尝试使用内置浏览器的 API 遍历 DOM 时，可能会遇到这些文本节点的问题。
```

2023-08-10 16:48 UTC, Jinjiang commented on src/glossary/index.md
> +## 提升 {#hoisting}
@vuejs-translations/zh-cn 想借这个机会讨论确认一下 hoist/hoisting 这个词的译法并加入 wiki 术语翻译约定。大家是否有“提升”以外的译法建议？谢谢

2023-08-10 16:49 UTC, Jinjiang commented on src/glossary/index.md
> +有许多种方式来指定组件的模板。在大多数情况下，模板是以字符串的形式提供的。
```suggestion
指定组件模板的方式有很多。在大多数情况下，模板是以字符串的形式提供的。
```

2023-08-10 16:51 UTC, Jinjiang commented on src/glossary/index.md
> +*内联 DOM 模板*一词指的是模板以 DOM 节点而非字符串的形式提供的场景。然后 Vue 将通过 `innerHTML` 将 DOM 节点转换为模板字符串。
```suggestion
*内联 DOM 模板*一词指的是以 DOM 节点而非字符串形式提供模板的场景。然后 Vue 将通过 `innerHTML` 将 DOM 节点转换为模板字符串。
```

2023-08-10 16:54 UTC, Jinjiang commented on src/glossary/index.md
> +## 内联 DOM 模板 {#in-dom-template}
@vuejs-translations/zh-cn 这里的译法也建议讨论确认并加入术语表，我之前参与过的译法是“DOM 内嵌模板”
如：https://cn.vuejs.org/guide/essentials/template-syntax.html#directives

2023-08-10 16:58 UTC, Jinjiang commented on src/glossary/index.md
> +在选项式 API 中，每个钩子都作为单独的选项提供，例如 `mounted`。而组合式 API 使用函数，例如 `onMounted()`。
```suggestion
在选项式 API 中，每个钩子都作为单独的选项提供，例如 `mounted`。而组合式 API 则使用函数，例如 `onMounted()`。
```

2023-08-11 01:58 UTC, wxsms commented on src/glossary/index.md
> +片段节点当前被渲染为 DOM 上的空文本节点，尽管这是一个实现细节。但如果你使用 `$el` 或尝试使用内置的浏览器 API 遍历 DOM 时，可能会遇到这些文本节点。
```suggestion
片段节点当前在 DOM 上被渲染为了空文本节点，但这只是一个实现细节。当你使用 `$el` 或尝试通过浏览器内置的 API 遍历 DOM 时，可能会遇到这些文本节点的问题。
```

微调：内置浏览器的->浏览器内置的

2023-08-11 02:00 UTC, wxsms commented on src/glossary/index.md
> +## 提升 {#hoisting}
https://developer.mozilla.org/zh-CN/docs/Glossary/Hoisting MDN 翻译为“变量提升”

2023-08-11 02:04 UTC, wxsms commented on src/glossary/index.md
> +## 内联 DOM 模板 {#in-dom-template}
建议“DOM 内联模板”

2023-08-11 02:37 UTC, Jinjiang commented on src/glossary/index.md
> +某些选项，例如 `props`、`emits` 和 `inheritAttrs`，可以在使用任一 API 编写组件时使用。由于它们是组件选项，因此它们可以被认为是选项式 API 的一部分。但是，由于这些选项也与 `setup()` 结合使用，因此通常更适合将它们视为两种组件风格之间共享的选项。
```suggestion
某些选项，例如 `props`、`emits` 和 `inheritAttrs`，可以用于任意一套 API 编写组件。由于它们是组件选项，因此可以被认为是选项式 API 的一部分。但是，由于这些选项也与 `setup()` 结合使用，因此通常更适合将它们视为两套组件风格之间共享的选项。
```

2023-08-11 02:37 UTC, Jinjiang commented on src/glossary/index.md
> +通过调用 `app.use(plugin)` 向应用中添加插件。插件本身可以是一个函数，也可以是一个带有 `install` 函数的对象。该函数将传递应用实例，然后可以执行任何所需的操作。
```suggestion
调用 `app.use(plugin)` 可以将插件添加到应用中。插件本身可以是一个函数，也可以是一个带有 `install` 函数的对象。该函数会被传入应用实例，然后执行任何所需的操作。
```

2023-08-11 02:37 UTC, Jinjiang commented on src/glossary/index.md
> +* 组件 props
```suggestion
* 组件 prop
```

2023-08-11 02:37 UTC, Jinjiang commented on src/glossary/index.md
> +* 插槽 props
props -> prop 下同

2023-08-11 02:37 UTC, Jinjiang commented on src/glossary/index.md
>  * VNode props
```suggestion
* VNode prop
```

2023-08-11 02:37 UTC, Jinjiang commented on src/glossary/index.md
> +*VNode props* 一词指的是作为 `h()` 的第二个参数传递的对象的属性。这些属性可以包括组件参数，但也可以包括组件事件、DOM 事件、DOM attribute 和 DOM property。通常只有在使用渲染函数直接操作 VNode 时才会用到 VNode props。
```suggestion
*VNode prop* 一词指的是作为第二个参数传入 `h()` 的对象的属性。这些属性可以包括组件 prop，也可以包括组件事件、DOM 事件、DOM attribute 和 DOM property。通常只有在使用渲染函数直接操作 VNode 时才会用到 VNode prop。
```

2023-08-11 02:37 UTC, Jinjiang commented on src/glossary/index.md
> +`watchEffect` 是最直接的创建作用的方式。Vue 的其他各个部分也会在内部使用作用。例如：组件渲染更新、`computed()` 和 `watch()`。
```suggestion
`watchEffect()` 是最直接的创建作用的方式。Vue 内部的其他各个部分也会使用作用。例如：组件渲染更新、`computed()` 和 `watch()`。
```

2023-08-11 02:37 UTC, Jinjiang commented on src/glossary/index.md
> +有多种不同的方式来实现一个响应性系统。例如，可以通过代码的静态分析来确定其依赖关系。但是，Vue 没有采用这种形式的响应性系统。
```suggestion
实现一个响应性系统的方式有很多种。例如，可以通过代码的静态分析来确定其依赖关系。但是，Vue 没有采用这种形式的响应性系统。
```

2023-08-11 02:37 UTC, Jinjiang commented on src/glossary/index.md
> +> 该条目是关于 `ref` 在响应性中的用法。对于模板中使用的 `ref` 属性，请参考[模板 ref](#template-ref)。
```suggestion
> 该条目是关于 `ref` 在响应性中的用法。对于模板中使用的 `ref` attribute，请参考[模板 ref](#template-ref)。
```

2023-08-14 02:11 UTC, Jinjiang commented on src/glossary/index.md
> +插槽用于向子组件传递内容。props 用于传递数据值，而插槽用于传递更丰富的内容，包括 HTML 元素和其他 Vue 组件。
```suggestion
插槽用于向子组件传递内容。和 prop 用于传递数据不同，插槽用于传递更丰富的内容，包括 HTML 元素和其他 Vue 组件。
```

2023-08-14 02:11 UTC, Jinjiang commented on src/glossary/index.md
> +*虚拟 DOM* (VDOM) 一词并非 Vue 独有。它是多个 Web 框架用于管理 UI 更新的常用方法。
```suggestion
*虚拟 DOM* (VDOM) 一词并非 Vue 独有。它是多个 web 框架用于管理 UI 更新的常用方法。
```

2023-08-14 02:11 UTC, Jinjiang commented on src/glossary/index.md
>  ## Web Component {#web-component}
@vuejs-translations/zh-cn 想重新讨论一下，大家觉得 web component(s) 要不要统一翻译成 web 组件？

2023-08-14 02:30 UTC, wxsms commented on src/glossary/index.md
>  ## SFC {#sfc}
赞同，不过部分英文 heading 原本就是不翻译的（如 prop），这部分就直接使用英文不做处理了吧？

2023-08-14 11:27 UTC, veaba commented on src/glossary/index.md
>  ## Web Component {#web-component}
不知道为什么，英文版本看起来故意要做出区分的。

- `async component`
- `Web Component`

2023-08-21 02:35 UTC, Jinjiang commented on src/glossary/index.md
>  ## SFC {#sfc}
恩，原本不翻译的我觉得就不必了，只特殊处理有中文翻译的

2023-08-22 03:10 UTC, Justineo requested changes

2023-08-22 03:10 UTC, Justineo commented on src/glossary/index.md
> +举个例子，在设置 `user.name = null` 属性的上下文中，预期 `user.name` 的值会被更改。如果它还做了其他事情，比如触发 Vue 的响应性系统，那么这就被描述为副作用。这就是 Vue 中的[响应式 effect](#reactive-effect) 一词的起源。
```suggestion
举个例子，在 `user.name = null` 这样设置属性的上下文中，我们可以预期 `user.name` 的值会被更改。如果它还做了其他事情，比如触发 Vue 的响应性系统，那么这就被描述为副作用。这就是 Vue 中的[响应式 effect](#reactive-effect) 一词的起源。
```

2023-08-23 01:37 UTC, Jinjiang commented
在此同步一下翻译团队的内部讨论结果：

* hoist/hoisting -> 提升/变量提升
* in-DOM templates -> DOM 内模板
* local -> 如果和 global 对应用局部，和 remote 对应用本地
* Web components -> 不翻译

相关内容会录入 wiki，大家有异议可以持续讨论

谢谢

2023-08-25 01:31 UTC, Jinjiang approved these changes

2023-08-25 01:32 UTC, merged