Update: Translated the events-props of the event
vuejs-translations/docs-zh-cn pull request #799
Opened 2023-12-19 04:48 UTC by huyikai

### 在创建 pull request 之前

请确认：

- [ ] 我已经阅读过项目的 [wiki](https://github.com/vuejs-translations/docs-zh-cn/wiki) 了解相关注意事项。
- [ ] 我对翻译内容的改动不包含基于英文原版的扩展、删减或演绎 (如有，请移步至[英文文档仓库](https://github.com/vuejs/docs)讨论，相关结论会被定期从英文版同步)

### 问题描述

2023-12-19 05:58 UTC, KiritaniAyaka requested changes

2023-12-19 05:58 UTC, KiritaniAyaka commented on src/guide/components/events.md
> +如果同时传递了 `:onEvent` 和 `@event`，`props.onEvent` 可能是 `functions` 的数组而不是 `function`，这种行为不稳定，可能会在未来改变。
```suggestion
如果同时传递了 `:onEvent` 和 `@event`，则 `props.onEvent` 可能是一个函数数组而不是单个函数，这种行为不稳定，可能会在未来改变。
```

这里虽然使用了反引号，但原文意思似乎并不是指代码中的某个 `function`/`functions` 符号，也许可以考虑将其翻译。

2023-12-19 05:58 UTC, KiritaniAyaka commented on src/guide/components/events.md
> +因此，建议在发出事件时使用 `emit('event')` 而不是 `props.onEvent`。
```suggestion
因此，建议在触发事件时使用 `emit('event')` 而不是 `props.onEvent`。
```

2023-12-19 05:58 UTC, KiritaniAyaka commented on src/guide/components/events.md
> +你也可以通过在大写的事件名称前加上 `on` 来声明并传递 `events` 作为 `props`
```suggestion
你也可以通过在大写的事件名称前加上 `on` 将 `events` 作为 `props` 声明并传递
```

2023-12-19 05:58 UTC, KiritaniAyaka commented on src/guide/components/events.md
> +## 事件作为属性 {#events-props}
个人认为翻译成「属性式事件」可能顺口些，但根据[约定](https://github.com/vuejs-translations/docs-zh-cn/wiki/%E7%BF%BB%E8%AF%91%E9%A1%BB%E7%9F%A5#1-%E6%9C%AF%E8%AF%AD%E7%BF%BB%E8%AF%91%E7%BA%A6%E5%AE%9A)，prop/props 不应该翻译，或者使用「props 式事件」？

2023-12-19 06:08 UTC, huyikai commented on src/guide/components/events.md
> +## 事件作为属性 {#events-props}
感谢指正，您的建议确实会更合理，内容已修改更新。

2023-12-20 02:02 UTC, wxsms commented on src/guide/components/events.md
> +## props 式事件 {#events-props}
```suggestion
## 将事件作为 prop {#events-props}
```

下文有出现同样的单词组合，建议这里保持一致。另外，”props 式事件“感觉像是一个专有名词，对应的英文可能是”Prop Event“，但是这里是 Event as props，感觉不太像是一个专有名词。

2023-12-20 02:12 UTC, merged