feat: add defineModel in sfc-script-setup.md
vuejs-translations/docs-zh-cn pull request #815
Opened 2024-01-02 07:00 UTC by shellingfordly

### 在创建 pull request 之前

请确认：

- [x] 我已经阅读过项目的 [wiki](https://github.com/vuejs-translations/docs-zh-cn/wiki) 了解相关注意事项。
- [x] 我对翻译内容的改动不包含基于英文原版的扩展、删减或演绎 (如有，请移步至[英文文档仓库](https://github.com/vuejs/docs)讨论，相关结论会被定期从英文版同步)

### 问题描述

2024-01-05 11:11 UTC, awxiaoxian2020 requested changes

2024-01-05 11:11 UTC, awxiaoxian2020 commented on src/api/sfc-script-setup.md
> +这个宏可以用来声明一个双向绑定属性，可以通过父组件的 `v-model` 来使用。[组件 `v-model`](/guide/components/v-model) 指南中也讨论了示例用法。
```suggestion
这个宏可以用来声明一个双向绑定属性，通过父组件的 `v-model` 来使用。[组件 `v-model`](/guide/components/v-model) 指南中也给出了示例用法。
```

2024-01-05 11:11 UTC, awxiaoxian2020 commented on src/api/sfc-script-setup.md
> +// 声明 “modelValue” 属性，由父节点通过v-model使用
```suggestion
// 声明 “modelValue” 属性，由父节点通过 v-model 使用
```
下同

2024-01-05 11:11 UTC, awxiaoxian2020 commented on src/api/sfc-script-setup.md
> +// 在发生改变时，触发事件 "update:modelValue"
```suggestion
// 在出现变化时，触发事件 "update:modelValue"
```

2024-01-05 11:11 UTC, awxiaoxian2020 commented on src/api/sfc-script-setup.md
> +当存在修饰符时，我们可能需要在读取或将其同步回父元素时对其值进行转换。我们可以通过使用 `get` 和 `set` 转换器选项来实现这一点
```suggestion
当存在修饰符时，我们可能需要在读取或将其同步回父元素时对其值进行转换。我们可以通过使用 `get` 和 `set` 转换器选项来实现这一点：
```

2024-01-11 09:25 UTC, Jinjiang commented
The conflict might need to be resolved due to the recent sync up from the English docs. Thanks.

2024-01-11 09:37 UTC, shellingfordly commented
> The conflict might need to be resolved due to the recent sync up from the English docs. Thanks.

Okay, I am resolving this conflict

2024-01-11 10:25 UTC, Justineo requested changes
这里有两个地方我感觉保留不翻译比较好，一个是 trim，一个是 model，可以大家一起看一下 /cc @vuejs-translations/zh-cn

2024-01-11 10:25 UTC, Justineo commented on src/api/sfc-script-setup.md
> +在底层，这个宏声明了一个属性和一个相应的值更新事件。如果第一个参数是一个字面值字符串，它将被用作属性名称；否则，属性名称将默认为 `"modelValue"`。在这两种情况下，你也可以传递一个额外的对象，它可以包括 prop 的选项和模型 ref 的值转换选项。
```suggestion
在底层，这个宏声明了一个 prop 和一个相应的值更新事件。如果第一个参数是一个字符串字面量，它将被用作 prop 名称；否则，prop 名称将默认为 `"modelValue"`。在这两种情况下，你都可以再传递一个额外的对象，它可以包含 prop 的选项和 model ref 的值转换选项。
```

2024-01-11 10:25 UTC, Justineo commented on src/api/sfc-script-setup.md
> +这个宏可以用来声明一个双向绑定属性，通过父组件的 `v-model` 来使用。[组件 `v-model`](/guide/components/v-model) 指南中也讨论了示例用法。
```suggestion
这个宏可以用来声明一个双向绑定 prop，通过父组件的 `v-model` 来使用。[组件 `v-model`](/guide/components/v-model) 指南中也讨论了示例用法。
```

2024-01-11 10:25 UTC, Justineo commented on src/api/sfc-script-setup.md
> +// 声明 “modelValue” 属性，由父节点通过 v-model 使用
```suggestion
// 声明 "modelValue" prop，由父组件通过 v-model 使用
```

2024-01-11 10:25 UTC, Justineo commented on src/api/sfc-script-setup.md
> +const model = defineModel();
不要添加分号，单引号也保留，下同

2024-01-11 10:25 UTC, Justineo commented on src/api/sfc-script-setup.md
> +// OR: 声明具有选项的 “modelValue” 属性
```suggestion
// 或者：声明带选项的 "modelValue" prop
```

2024-01-11 10:25 UTC, Justineo commented on src/api/sfc-script-setup.md
> +// 在出现变化时，触发事件 "update:modelValue"
```suggestion
// 在被修改时，触发 "update:modelValue" 事件
```

2024-01-11 10:25 UTC, Justineo commented on src/api/sfc-script-setup.md
> +// 声明 "count" 属性，由父节点通过v-model:count使用
```suggestion
// 声明 "count" prop，由父组件通过 v-model:count 使用
```

2024-01-11 10:25 UTC, Justineo commented on src/api/sfc-script-setup.md
> +// OR: 声明带有选项的 “count” 属性
```suggestion
// 或者：声明带选项的 "count" prop
```

2024-01-11 10:25 UTC, Justineo commented on src/api/sfc-script-setup.md
> +  // 在发生改变时，触发事件 "update:count"
```suggestion
  // 在被修改时，触发 "update:count" 事件
```

2024-01-11 10:25 UTC, Justineo commented on src/api/sfc-script-setup.md
> +为了访问 `v-model` 指令使用的修饰符，我们可以像这样解构 `defineModel()` 的返回值：
```suggestion
为了获取 `v-model` 指令使用的修饰符，我们可以像这样解构 `defineModel()` 的返回值：
```

2024-01-11 10:25 UTC, Justineo commented on src/api/sfc-script-setup.md
> +当存在修饰符时，我们可能需要在读取或将其同步回父元素时对其值进行转换。我们可以通过使用 `get` 和 `set` 转换器选项来实现这一点：
```suggestion
当存在修饰符时，我们可能需要在读取或将其同步回父组件时对其值进行转换。我们可以通过使用 `get` 和 `set` 转换器选项来实现这一点：
```

2024-01-11 10:25 UTC, Justineo commented on src/api/sfc-script-setup.md
> +    // 如果使用.trim修饰符，则返回处理过的值
```suggestion
    // 如果使用了 .trim 修饰符，则返回 trim 过的值
```

我感觉这个可能不翻译更好

2024-01-11 10:25 UTC, Justineo commented on src/api/sfc-script-setup.md
> +    // 否则，按原样返回值
```suggestion
    // 否则，原样返回
```

2024-01-11 10:25 UTC, Justineo commented on src/api/sfc-script-setup.md
> +### TypeScript 用法 <sup class="vt-badge ts" /> {#usage-with-typescript}
```suggestion
### 在 TypeScript 中使用 <sup class="vt-badge ts" /> {#usage-with-typescript}
```

2024-01-11 10:25 UTC, Justineo commented on src/api/sfc-script-setup.md
> +与 `defineProps` 和 `defineEmits` 一样，`defineModel` 也可以接收类型参数来指定模型值和修饰符的类型
```suggestion
与 `defineProps` 和 `defineEmits` 一样，`defineModel` 也可以接收类型参数来指定 model 值和修饰符的类型：
```

2024-01-11 10:25 UTC, Justineo commented on src/api/sfc-script-setup.md
> +// 带有选项的默认模型，required 删除可能的未定义值
```suggestion
// 用带有选项的默认 model，设置 required 去掉了可能的 undefined 值
```

这个我觉得可以突出下和上面没有选项的用法的对比。

2024-01-11 11:37 UTC, shellingfordly commented on src/api/sfc-script-setup.md
> +在底层，这个宏声明了一个属性和一个相应的值更新事件。如果第一个参数是一个字面值字符串，它将被用作属性名称；否则，属性名称将默认为 `"modelValue"`。在这两种情况下，你也可以传递一个额外的对象，它可以包括 prop 的选项和模型 ref 的值转换选项。
好的

2024-01-15 04:15 UTC, Jinjiang commented on src/api/sfc-script-setup.md
> +在底层，这个宏声明了一个 prop 和一个相应的值更新事件。如果第一个参数是一个字符串字面量，它将被用作 prop 名称；否则，prop 名称将默认为 `"modelValue"`。在这两种情况下，你都可以再传递一个额外的对象，它可以包含 prop 的选项和 model ref 的值转换选项。
```suggestion
在底层，这个宏声明了一个 model prop 和一个相应的值更新事件。如果第一个参数是一个字符串字面量，它将被用作 prop 名称；否则，prop 名称将默认为 `"modelValue"`。在这两种情况下，你都可以再传递一个额外的对象，它可以包含 prop 的选项和 model ref 的值转换选项。
```

2024-01-15 04:15 UTC, Jinjiang commented on src/api/sfc-script-setup.md
> +    // 如果使用了 .trim 修饰符，则返回 trim 过的值
```suggestion
    // 如果使用了 .trim 修饰符，则返回裁剪后过的值
```

解释一下，这里译为“裁剪”在中文里并不十分准确，但暂没有想到更好的译法且句子前半句已经有 .trim 了，所以不太会造成歧义。同样因为句子中已经有 .trim，对于读者来说不翻译的话信息量就变得更少了。所以和 @Justineo 简单交流之后最终选择此译法。谢谢。

2024-01-15 04:16 UTC, Jinjiang approved these changes

2024-01-15 04:17 UTC, merged