translate TODO in application.md
vuejs-translations/docs-zh-cn pull request #828
Opened 2024-01-15 02:33 UTC by awxiaoxian2020

### 在创建 pull request 之前

请确认：

- [x] 我已经阅读过项目的 [wiki](https://github.com/vuejs-translations/docs-zh-cn/wiki) 了解相关注意事项。
- [x] 我对翻译内容的改动不包含基于英文原版的扩展、删减或演绎 (如有，请移步至[英文文档仓库](https://github.com/vuejs/docs)讨论，相关结论会被定期从英文版同步)

2024-01-24 00:06 UTC, awxiaoxian2020 commented
👀

2024-01-26 05:29 UTC, Justineo requested changes

2024-01-26 05:29 UTC, Justineo commented on src/api/composition-api-lifecycle.md
> +  在生产环境中，第三个参数 (`info`) 不是含有完整信息的字符串，而是一串较短的代码。代码和字符串的映射可以参阅[生产环境错误代码参考](/error-reference/#runtime-errors)。
```suggestion
  在生产环境中，第三个参数 (`info`) 是一个缩短的代码，而不是含有完整信息的字符串。错误代码和字符串的映射可以参阅[生产环境错误代码参考](/error-reference/#runtime-errors)。
```

2024-01-26 05:29 UTC, Justineo commented on src/api/options-lifecycle.md
> +  在生产环境中，第三个参数 (`info`) 不是含有完整信息的字符串，而是一串较短的代码。代码和字符串的映射可以参阅[生产环境错误代码参考](/error-reference/#runtime-errors)。
```suggestion
  在生产环境中，第三个参数 (`info`) 是一个缩短的代码，而不是含有完整信息的字符串。错误代码和字符串的映射可以参阅[生产环境错误代码参考](/error-reference/#runtime-errors)。
```

2024-01-26 05:29 UTC, Justineo commented on src/error-reference/index.md
> +在生产环境中，传递给以下错误处理程序 API 的第三个参数不是含有完整信息的字符串，而是一串较短的代码。
```suggestion
在生产环境中，传递给以下错误处理程序 API 的第三个参数是一个短代码，而不是含有完整信息的字符串：
```

2024-01-26 05:29 UTC, merged