docs: translate jsx-type-inference
vuejs-translations/docs-zh-cn pull request #836
Opened 2024-01-24 02:16 UTC by Ares-Chang

### 在创建 pull request 之前

请确认：
- [x] 我已经阅读过项目的 [wiki](https://github.com/vuejs-translations/docs-zh-cn/wiki) 了解相关注意事项。
- [x] 我对翻译内容的改动不包含基于英文原版的扩展、删减或演绎 (如有，请移步至[英文文档仓库](https://github.com/vuejs/docs)讨论，相关结论会被定期从英文版同步)

### 问题描述

翻译 JSX 类型推断一段内容，设置 ts + jsx 类型配置

2024-01-24 03:10 UTC, KiritaniAyaka requested changes

2024-01-24 03:10 UTC, KiritaniAyaka commented on src/guide/extras/render-function.md
> +从 Vue 3.4 开始，Vue 不再隐式注册全局 `JSX` 命名空间。要指示 TypeScript 使用 Vue 的 JSX 类型定义，请确保在您的 `tsconfig.json` 中包含以下内容：
```suggestion
从 Vue 3.4 开始，Vue 不再隐式注册全局 `JSX` 命名空间。要指示 TypeScript 使用 Vue 的 JSX 类型定义，请确保在你的 `tsconfig.json` 中包含以下内容：
```

根据[术语翻译约定](https://github.com/vuejs-translations/docs-zh-cn/wiki/%E7%BF%BB%E8%AF%91%E9%A1%BB%E7%9F%A5#1-%E6%9C%AF%E8%AF%AD%E7%BF%BB%E8%AF%91%E7%BA%A6%E5%AE%9A)

2024-01-24 03:40 UTC, Ares-Chang commented on src/guide/extras/render-function.md
> +从 Vue 3.4 开始，Vue 不再隐式注册全局 `JSX` 命名空间。要指示 TypeScript 使用 Vue 的 JSX 类型定义，请确保在您的 `tsconfig.json` 中包含以下内容：
Thanks，没什么经验，感谢

2024-01-26 05:30 UTC, Justineo approved these changes

2024-01-26 05:31 UTC, merged