Update: translate src/guide/built-ins/transition.md
vuejs-translations/docs-zh-cn pull request #884
Opened 2024-03-12 07:48 UTC by Aaron-zon

### 在创建 pull request 之前

请确认：

- [x] 我已经阅读过项目的 [wiki](https://github.com/vuejs-translations/docs-zh-cn/wiki) 了解相关注意事项。
- [x] 我对翻译内容的改动不包含基于英文原版的扩展、删减或演绎 (如有，请移步至[英文文档仓库](https://github.com/vuejs/docs)讨论，相关结论会被定期从英文版同步)

### 问题描述
translate:  Transitions with the Key Attribute

2024-03-12 13:38 UTC, KiritaniAyaka requested changes
根据[翻译属于约定](https://github.com/vuejs-translations/docs-zh-cn/wiki/%E7%BF%BB%E8%AF%91%E9%A1%BB%E7%9F%A5#1-%E6%9C%AF%E8%AF%AD%E7%BF%BB%E8%AF%91%E7%BA%A6%E5%AE%9A)保留 attribute

2024-03-12 13:38 UTC, KiritaniAyaka commented on src/guide/built-ins/transition.md
> +如果我们没有 `key` 属性，则只有文本节点会被更新，因此不会发生过渡。但是，有了 `key` 属性，Vue 就知道在 `count` 改变时创建了一个新的 `span` 元素，因此 `Transition` 组件有两个不同的元素在它们之间进行过渡。
```suggestion
如果不使用 `key` attribute，则只有文本节点会被更新，因此不会发生过渡。但是，有了 `key` 属性，Vue 就知道在 `count` 改变时创建一个新的 `span` 元素，因此 `Transition` 组件有两个不同的元素在它们之间进行过渡。
```

2024-03-12 13:38 UTC, KiritaniAyaka commented on src/guide/built-ins/transition.md
> +## 使用Key属性过渡 {#transitions-with-the-key-attribute}
```suggestion
## 使用 Key Attribute 过渡 {#transitions-with-the-key-attribute}
```

2024-03-12 13:38 UTC, KiritaniAyaka commented on src/guide/built-ins/transition.md
> +有时，你需要强制重新渲染一个 DOM 元素时进行过渡。
```suggestion
有时为了触发过渡，你需要强制重新渲染 DOM 元素。
```

2024-03-20 10:55 UTC, veaba approved these changes

2024-03-20 10:56 UTC, merged