Update: translate `privacy.md`
vuejs-translations/docs-zh-cn pull request #939
Opened 2024-05-15 01:40 UTC by huyikai

### 在创建 pull request 之前

请确认：

- [x] 我已经阅读过项目的 [wiki](https://github.com/vuejs-translations/docs-zh-cn/wiki) 了解相关注意事项。
- [x] 我对翻译内容的改动不包含基于英文原版的扩展、删减或演绎 (如有，请移步至[英文文档仓库](https://github.com/vuejs/docs)讨论，相关结论会被定期从英文版同步)

### 问题描述

2024-05-15 01:50 UTC, xiaodong2008 requested changes
lint issues

2024-05-23 02:24 UTC, wxsms commented
欢迎贡献，请参考我们的 wiki 指南，按照约定的格式使用标点符号，如使用半角而非全角括号，并建议在翻译完成后使用项目内的 zhlint 工具检查格式。谢谢。

2024-05-24 02:06 UTC, huyikai commented
> 欢迎贡献，请参考我们的 wiki 指南，按照约定的格式使用标点符号，如使用半角而非全角括号，并建议在翻译完成后使用项目内的 zhlint 工具检查格式。谢谢。

感谢指导。已更新内容。

2024-05-24 04:29 UTC, xiaodong2008 requested changes

2024-05-24 04:29 UTC, xiaodong2008 commented on src/about/privacy.md
> +- **搜索功能的使用数据。**我们的搜索功能由 [Algolia DocSearch](https://docsearch.algolia.com/) 提供支持，该服务不进行任何形式的用户追踪或指纹识别，也不使用 cookies。Algolia 的服务符合 GPDR、CCPA 标准，并获得 TRUSTe 认证。
此处的 `powered by` 应翻译为 `驱动`，而不是 `提供支持`

2024-05-24 04:29 UTC, xiaodong2008 commented on src/about/privacy.md
> +2. 在 GitHub 上参与开源项目的拉取请求、问题以及任何其他交互或功能，这些都受 GitHub 的条款和条件的约束；
无需翻译为 `拉取请求`，`PR` 即可

2024-05-24 04:32 UTC, xiaodong2008 commented on src/about/privacy.md
> +2. 在 GitHub 上参与开源项目的拉取请求、问题以及任何其他交互或功能，这些都受 GitHub 的条款和条件的约束；
同样，`Issue` 无需翻译为 `问题`

2024-05-24 04:42 UTC, xiaodong2008 approved these changes

2024-05-29 02:53 UTC, wxsms commented on src/about/privacy.md
> +本隐私政策描述了 Vue.js 组织 (以下简称“Vue”、“我们”) 在本网站 (<https://vuejs.org>) 及我们的开源相关网站 (以下统称“网站”) 上处理您信息的做法，以及在本网站上向您提供的任何内容、相关文档、信息和服务 (例如教程、支持开发者工作流的工具、资源访问等)(统称“服务”)。本隐私政策阐述了我们如何处理个人信息来支持我们的服务。
```suggestion
本隐私政策描述了 Vue.js 组织 (以下简称“Vue”、“我们”或“我们的”) 在本网站 (<https://vuejs.org>) 及我们的开源相关网站 (以下统称“网站”) ，以及在本网站上向您提供的任何内容、相关文档、信息和服务 (例如教程、支持开发者工作流的工具、资源访问等)(统称“服务”)上处理您的信息的做法。本隐私政策阐述了我们如何处理个人信息来支持我们的服务。
```

2024-05-29 02:54 UTC, merged