docs(provide-inject): src/guide/components/provide-inject.md #94
vuejs-translations/docs-zh-cn pull request #96
Opened 2022-02-17 09:04 UTC by web-wgf

翻译部分没有翻译完全的地方

2022-02-18 08:39 UTC, 1sm23 commented on src/guide/components/provide-inject.md
> +当使用响应式`provide`注入值时，**建议在创建`provide`的时候提供响应式的状态和更改状态的方法**。 这样可以确保`provide`的状态和变更操作都在同一个组件内，使其更容易维护。
当使用响应式 `provide` 注入值时
中英文之间没加空格

2022-02-18 08:40 UTC, 1sm23 requested changes
中英文之间没加空格
例如
当使用响应式 `provide` 注入值时

2022-02-18 09:25 UTC, web-wgf commented
> 中英文之间没加空格 例如 当使用响应式 `provide` 注入值时

好的

2022-02-18 09:32 UTC, web-wgf commented
中英文之间加空格已修改

2022-02-27 14:54 UTC, veaba commented on src/guide/components/provide-inject.md
> +最后，如果你想确保从 `provide` 传过来的数据不能被 `injector` 的组件更改，你可以使用[`readonly()`](/api/reactivity-core.html#readonly) 来包装提供的值。
```suggestion
最后，如果你想确保从 `provide` 传过来的数据不能被 `injector` 的组件更改，你可以使用[`readonly()`](/api/reactivity-core.html#readonly) 来包裹提供的值。
```

2022-02-27 14:55 UTC, veaba commented on src/guide/components/provide-inject.md
> +你也可以看看：[为 Provide / Inject 标注类型](/guide/typescript/composition-api.html#typing-provide-inject) <sup class="vt-badge ts">TS</sup>
```suggestion
请查看：[为 Provide / Inject 标注类型](/guide/typescript/composition-api.html#typing-provide-inject) <sup class="vt-badge ts">TS</sup>
```

2022-02-27 15:06 UTC, veaba commented on src/guide/components/provide-inject.md
> +当使用响应式 `provide` 注入值时，**建议在创建 `provide` 的时候提供响应式的状态和更改状态的方法**。 这样可以确保 `provide` 的状态和变更操作都在同一个组件内，使其更容易维护。
```suggestion
当使用响应式 `provide`/`inject` 值时，**建议尽可能将任何对反应式状态的变更都保持在*提供者*内部**。 这样可以确保 `provide` 的状态和变更操作都在同一个组件内，使其更容易维护。
```

2022-02-27 15:08 UTC, merged

2022-02-27 15:09 UTC, veaba commented
close #94